// automatically generated by the FlatBuffers compiler, do not modify



pub mod MyGame {
  #[allow(unused_imports)]
  use std::mem;
  #[allow(unused_imports)]
  use std::marker::PhantomData;
  #[allow(unused_imports)]
  #[allow(unreachable_code)]
  extern crate flatbuffers;
  #[allow(unused_imports)]
  use self::flatbuffers::flexbuffers;
  #[allow(unused_imports)]
  use std::cmp::Ordering;

pub struct InParentNamespace {}
impl flatbuffers::Table for InParentNamespace {}
impl InParentNamespace /* private flatbuffers::Table */ {
  fn Verify(&self, verifier: &flatbuffers::Verifier) -> bool {
    return flatbuffers::verify_table_start(verifier) &&
           verifier.end_table();
  }
}

pub struct InParentNamespaceBuilder<'a> {
  fbb_: &'a flatbuffers::FlatBufferBuilder,
  start_: flatbuffers::UOffsetT,
}
impl<'a> InParentNamespaceBuilder<'a> {
  fn new(_fbb: &mut flatbuffers::FlatBufferBuilder) -> InParentNamespaceBuilder {
    InParentNamespaceBuilder {
      fbb_: _fbb,
      start_: _fbb.start_table(),
    }
  }
  // InParentNamespaceBuilder &operator=(const InParentNamespaceBuilder &);
  fn finish(&mut self) -> flatbuffers::Offset<InParentNamespace> {
    let end = self.fbb_.end_table(self.start_);
    let o = flatbuffers::Offset::<InParentNamespace>::new(end);
    o
  }
}

#[inline]
fn CreateInParentNamespace(
    _fbb: &mut flatbuffers::FlatBufferBuilder) -> flatbuffers::Offset<InParentNamespace> {
  let mut builder = InParentNamespaceBuilder::new(_fbb);
  builder.finish()
}

#[inline]
fn InParentNamespaceTypeTable() -> /*&mut?*/flatbuffers::TypeTable {
  return flatbuffers::TypeTable{};
  /* disable type table for now
  static flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 0, nullptr, nullptr, nullptr, nullptr
  };
  return &tt;
  */
}

pub mod Example2 {
  #[allow(unused_imports)]
  use std::mem;
  #[allow(unused_imports)]
  use std::marker::PhantomData;
  #[allow(unused_imports)]
  #[allow(unreachable_code)]
  extern crate flatbuffers;
  #[allow(unused_imports)]
  use self::flatbuffers::flexbuffers;
  #[allow(unused_imports)]
  use std::cmp::Ordering;

pub struct Monster {}
impl flatbuffers::Table for Monster {}
impl Monster /* private flatbuffers::Table */ {
  fn Verify(&self, verifier: &flatbuffers::Verifier) -> bool {
    return flatbuffers::verify_table_start(verifier) &&
           verifier.end_table();
  }
}

pub struct MonsterBuilder<'a> {
  fbb_: &'a flatbuffers::FlatBufferBuilder,
  start_: flatbuffers::UOffsetT,
}
impl<'a> MonsterBuilder<'a> {
  fn new(_fbb: &mut flatbuffers::FlatBufferBuilder) -> MonsterBuilder {
    MonsterBuilder {
      fbb_: _fbb,
      start_: _fbb.start_table(),
    }
  }
  // MonsterBuilder &operator=(const MonsterBuilder &);
  fn finish(&mut self) -> flatbuffers::Offset<Monster> {
    let end = self.fbb_.end_table(self.start_);
    let o = flatbuffers::Offset::<Monster>::new(end);
    o
  }
}

#[inline]
fn CreateMonster(
    _fbb: &mut flatbuffers::FlatBufferBuilder) -> flatbuffers::Offset<Monster> {
  let mut builder = MonsterBuilder::new(_fbb);
  builder.finish()
}

#[inline]
fn MonsterTypeTable() -> /*&mut?*/flatbuffers::TypeTable {
  return flatbuffers::TypeTable{};
  /* disable type table for now
  static flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 0, nullptr, nullptr, nullptr, nullptr
  };
  return &tt;
  */
}

}  // pub mod Example2

pub mod Example {
  #[allow(unused_imports)]
  use std::mem;
  #[allow(unused_imports)]
  use std::marker::PhantomData;
  #[allow(unused_imports)]
  #[allow(unreachable_code)]
  extern crate flatbuffers;
  #[allow(unused_imports)]
  use self::flatbuffers::flexbuffers;
  #[allow(unused_imports)]
  use std::cmp::Ordering;

#[repr(i8)]
enum Color {
  Red = 1,
  Green = 2,
  Blue = 8
}

const EnumValuesColor:[Color; 3] = [
  Color::Red,
  Color::Green,
  Color::Blue
];

const EnumNamesColor:[&'static str; 8] = [
    "Red",
    "Green",
    "",
    "",
    "",
    "",
    "",
    "Blue"
];

fn EnumNameColor(e: Color) -> &'static str {
  let index: usize = e as usize - Color::Red as usize;
  EnumNamesColor[index]
}

#[repr(u8)]
enum Any {
  NONE = 0,
  Monster = 1,
  TestSimpleTableWithEnum = 2,
  MyGame_Example2_Monster = 3
}

const EnumValuesAny:[Any; 4] = [
  Any::NONE,
  Any::Monster,
  Any::TestSimpleTableWithEnum,
  Any::MyGame_Example2_Monster
];

const EnumNamesAny:[&'static str; 4] = [
    "NONE",
    "Monster",
    "TestSimpleTableWithEnum",
    "MyGame_Example2_Monster"
];

fn EnumNameAny(e: Any) -> &'static str {
  let index: usize = e as usize;
  EnumNamesAny[index]
}

// MANUALLY_ALIGNED_STRUCT(2)
#[repr(C, packed)]
pub struct Test {
  a_: i16,
  b_: i8,
  padding0__: u8,
} // pub struct Test

impl Test {
  fn Reset(&mut self) {
    //memset(this, 0, size_of(Test));
  }
  fn init(&mut self, _a: i16, _b: i8) {
      self.a_ = flatbuffers::endian_scalar(_a);
      self.b_ = flatbuffers::endian_scalar(_b);

  }
  fn a(&self) -> i16  {
    flatbuffers::endian_scalar(self.a_)
  }
  fn mutate_a(&mut self, _a: i16) {
    flatbuffers::write_scalar(&self.a_, _a);
  }
  fn b(&self) -> i8  {
    flatbuffers::endian_scalar(self.b_)
  }
  fn mutate_b(&mut self, _b: i8) {
    flatbuffers::write_scalar(&self.b_, _b);
  }
}
// STRUCT_END(Test, 4);

// MANUALLY_ALIGNED_STRUCT(16)
#[repr(C, packed)]
pub struct Vec3<'a> {
  x_: f32,
  y_: f32,
  z_: f32,
  padding0__: u32,
  test1_: f64,
  test2_: i8,
  padding1__: u8,
  test3_: &'a Test,
  padding2__: u16,
} // pub struct Vec3

impl<'a> Vec3<'a> {
  fn Reset(&mut self) {
    //memset(this, 0, size_of(Vec3));
  }
  fn init(&mut self, _x: f32, _y: f32, _z: f32, _test1: f64, _test2: Color, _test3: &'a Test) {
      self.x_ = _x;
      self.y_ = _y;
      self.z_ = _z;
      self.test1_ = _test1;
      self.test2_ = flatbuffers::endian_scalar(_test2 as i8);
      self.test3_ = _test3;

  }
  fn x(&self) -> f32  {
    self.x_
  }
  fn mutable_x(&mut self) -> &mut f32 {
    &mut self.x_
  }
  fn y(&self) -> f32  {
    self.y_
  }
  fn mutable_y(&mut self) -> &mut f32 {
    &mut self.y_
  }
  fn z(&self) -> f32  {
    self.z_
  }
  fn mutable_z(&mut self) -> &mut f32 {
    &mut self.z_
  }
  fn test1(&self) -> f64  {
    self.test1_
  }
  fn mutable_test1(&mut self) -> &mut f64 {
    &mut self.test1_
  }
  fn test2(&self) -> Color  {
    EnumValuesColor[flatbuffers::endian_scalar(self.test2_) as usize]
  }
  fn mutate_test2(&mut self, _test2: Color) {
    flatbuffers::write_scalar(&self.test2_, _test2 as i8);
  }
  fn test3(&self) -> &Test {
    self.test3_
  }
  fn mutable_test3(&mut self) -> &mut Test {
    &mut self.test3_
  }
}
// STRUCT_END(Vec3, 32);

// MANUALLY_ALIGNED_STRUCT(4)
#[repr(C, packed)]
pub struct Ability {
  id_: u32,
  distance_: u32,
} // pub struct Ability

impl Ability {
  fn Reset(&mut self) {
    //memset(this, 0, size_of(Ability));
  }
  fn init(&mut self, _id: u32, _distance: u32) {
      self.id_ = flatbuffers::endian_scalar(_id);
      self.distance_ = flatbuffers::endian_scalar(_distance);

  }
  fn id(&self) -> u32  {
    flatbuffers::endian_scalar(self.id_)
  }
  fn mutate_id(&mut self, _id: u32) {
    flatbuffers::write_scalar(&self.id_, _id);
  }
  fn KeyCompareLessThan(&self, o: &Ability) -> bool {
    self.id() < o.id()
  }
  fn KeyCompareWithValue(&self, val: u32) -> isize {
    let key = self.id();
    (key > val) as isize - (key < val) as isize
  }
  fn distance(&self) -> u32  {
    flatbuffers::endian_scalar(self.distance_)
  }
  fn mutate_distance(&mut self, _distance: u32) {
    flatbuffers::write_scalar(&self.distance_, _distance);
  }
}
// STRUCT_END(Ability, 8);

pub struct TestSimpleTableWithEnum {}
impl flatbuffers::Table for TestSimpleTableWithEnum {}
impl TestSimpleTableWithEnum /* private flatbuffers::Table */ {
    const VT_COLOR: isize = 4;

  fn color(&self) -> Color  {
    // yo
    EnumValuesColor[flatbuffers::get_field::<i8>(TestSimpleTableWithEnum::VT_COLOR, 2) as usize]
  }
  fn mutate_color(&mut self, color_: Color) -> bool {
    flatbuffers::set_field::<i8>(TestSimpleTableWithEnum::VT_COLOR, color_ as i8, 2)
  }
  fn Verify(&self, verifier: &flatbuffers::Verifier) -> bool {
    return flatbuffers::verify_table_start(verifier) &&
           flatbuffers::verify_field::<i8>(verifier, TestSimpleTableWithEnum::VT_COLOR) &&
           verifier.end_table();
  }
}

pub struct TestSimpleTableWithEnumBuilder<'a> {
  fbb_: &'a flatbuffers::FlatBufferBuilder,
  start_: flatbuffers::UOffsetT,
}
impl<'a> TestSimpleTableWithEnumBuilder<'a> {
  fn add_color(&mut self, color: Color ) {
    self.fbb_.add_element::<i8>(TestSimpleTableWithEnum::VT_COLOR, color as i8, 2);
  }
  fn new(_fbb: &mut flatbuffers::FlatBufferBuilder) -> TestSimpleTableWithEnumBuilder {
    TestSimpleTableWithEnumBuilder {
      fbb_: _fbb,
      start_: _fbb.start_table(),
    }
  }
  // TestSimpleTableWithEnumBuilder &operator=(const TestSimpleTableWithEnumBuilder &);
  fn finish(&mut self) -> flatbuffers::Offset<TestSimpleTableWithEnum> {
    let end = self.fbb_.end_table(self.start_);
    let o = flatbuffers::Offset::<TestSimpleTableWithEnum>::new(end);
    o
  }
}

#[inline]
fn CreateTestSimpleTableWithEnum(
    _fbb: &mut flatbuffers::FlatBufferBuilder,
    color: Color  /* = Color::Green */) -> flatbuffers::Offset<TestSimpleTableWithEnum> {
  let mut builder = TestSimpleTableWithEnumBuilder::new(_fbb);
  builder.add_color(color);
  builder.finish()
}

pub struct Stat {}
impl flatbuffers::Table for Stat {}
impl Stat /* private flatbuffers::Table */ {
    const VT_ID: isize = 4;
    const VT_VAL: isize = 6;
    const VT_COUNT: isize = 8;

  fn id(&self) -> &flatbuffers::String  {
    // yo
    flatbuffers::get_pointer::<&flatbuffers::String>(Stat::VT_ID)
  }
  fn mutable_id(&mut self) -> &mut flatbuffers::String  {
    /* TODO: are there non-reference choices here? */
    &mut flatbuffers::get_pointer::<&mut flatbuffers::String >(Stat::VT_ID)
  }
  fn val(&self) -> i64  {
    // yo
    flatbuffers::get_field::<i64>(Stat::VT_VAL, 0)
  }
  fn mutate_val(&mut self, val_: i64) -> bool {
    flatbuffers::set_field::<i64>(Stat::VT_VAL, val_, 0)
  }
  fn count(&self) -> u16  {
    // yo
    flatbuffers::get_field::<u16>(Stat::VT_COUNT, 0)
  }
  fn mutate_count(&mut self, count_: u16) -> bool {
    flatbuffers::set_field::<u16>(Stat::VT_COUNT, count_, 0)
  }
  fn Verify(&self, verifier: &flatbuffers::Verifier) -> bool {
    return flatbuffers::verify_table_start(verifier) &&
           flatbuffers::verify_offset(verifier, Stat::VT_ID) &&
           verifier.verify(self.id()) &&
           flatbuffers::verify_field::<i64>(verifier, Stat::VT_VAL) &&
           flatbuffers::verify_field::<u16>(verifier, Stat::VT_COUNT) &&
           verifier.end_table();
  }
}

pub struct StatBuilder<'a> {
  fbb_: &'a flatbuffers::FlatBufferBuilder,
  start_: flatbuffers::UOffsetT,
}
impl<'a> StatBuilder<'a> {
  fn add_id(&mut self, id: flatbuffers::Offset<flatbuffers::String> ) {
    self.fbb_.add_offset(Stat::VT_ID, id);
  }
  fn add_val(&mut self, val: i64 ) {
    self.fbb_.add_element::<i64>(Stat::VT_VAL, val, 0);
  }
  fn add_count(&mut self, count: u16 ) {
    self.fbb_.add_element::<u16>(Stat::VT_COUNT, count, 0);
  }
  fn new(_fbb: &mut flatbuffers::FlatBufferBuilder) -> StatBuilder {
    StatBuilder {
      fbb_: _fbb,
      start_: _fbb.start_table(),
    }
  }
  // StatBuilder &operator=(const StatBuilder &);
  fn finish(&mut self) -> flatbuffers::Offset<Stat> {
    let end = self.fbb_.end_table(self.start_);
    let o = flatbuffers::Offset::<Stat>::new(end);
    o
  }
}

#[inline]
fn CreateStat(
    _fbb: &mut flatbuffers::FlatBufferBuilder,
    id: flatbuffers::Offset<flatbuffers::String>  /* = 0 */,
    val: i64  /* = 0 */,
    count: u16  /* = 0 */) -> flatbuffers::Offset<Stat> {
  let mut builder = StatBuilder::new(_fbb);
  builder.add_val(val);
  builder.add_id(id);
  builder.add_count(count);
  builder.finish()
}

#[inline]
fn CreateStatDirect(
    _fbb: &mut flatbuffers::FlatBufferBuilder,
    id: Option<&str> /* = nullptr */,
    val: i64  /* = 0 */,
    count: u16  /* = 0 */) -> flatbuffers::Offset<Stat> {
  return CreateStat(
      _fbb,
      if let Some(x) = id { _fbb.create_string(x) } else { flatbuffers::Offset::new(0) },
      val,
      count);
}

/// an example documentation comment: monster object
pub struct Monster {}
impl flatbuffers::Table for Monster {}
impl Monster /* private flatbuffers::Table */ {
    const VT_POS: isize = 4;
    const VT_MANA: isize = 6;
    const VT_HP: isize = 8;
    const VT_NAME: isize = 10;
    const VT_INVENTORY: isize = 14;
    const VT_COLOR: isize = 16;
    const VT_TEST_TYPE: isize = 18;
    const VT_TEST: isize = 20;
    const VT_TEST4: isize = 22;
    const VT_TESTARRAYOFSTRING: isize = 24;
    const VT_TESTARRAYOFTABLES: isize = 26;
    const VT_ENEMY: isize = 28;
    const VT_TESTNESTEDFLATBUFFER: isize = 30;
    const VT_TESTEMPTY: isize = 32;
    const VT_TESTBOOL: isize = 34;
    const VT_TESTHASHS32_FNV1: isize = 36;
    const VT_TESTHASHU32_FNV1: isize = 38;
    const VT_TESTHASHS64_FNV1: isize = 40;
    const VT_TESTHASHU64_FNV1: isize = 42;
    const VT_TESTHASHS32_FNV1A: isize = 44;
    const VT_TESTHASHU32_FNV1A: isize = 46;
    const VT_TESTHASHS64_FNV1A: isize = 48;
    const VT_TESTHASHU64_FNV1A: isize = 50;
    const VT_TESTARRAYOFBOOLS: isize = 52;
    const VT_TESTF: isize = 54;
    const VT_TESTF2: isize = 56;
    const VT_TESTF3: isize = 58;
    const VT_TESTARRAYOFSTRING2: isize = 60;
    const VT_TESTARRAYOFSORTEDSTRUCT: isize = 62;
    const VT_FLEX: isize = 64;
    const VT_TEST5: isize = 66;
    const VT_VECTOR_OF_LONGS: isize = 68;
    const VT_VECTOR_OF_DOUBLES: isize = 70;
    const VT_PARENT_NAMESPACE_TEST: isize = 72;

  fn pos(&self) -> &Vec3  {
    // yo
    flatbuffers::get_struct::<&Vec3>(Monster::VT_POS)
  }
  fn mutable_pos(&mut self) -> &mut Vec3  {
    /* TODO: are there non-reference choices here? */
    &mut flatbuffers::get_struct::<&mut Vec3 >(Monster::VT_POS)
  }
  fn mana(&self) -> i16  {
    // yo
    flatbuffers::get_field::<i16>(Monster::VT_MANA, 150)
  }
  fn mutate_mana(&mut self, mana_: i16) -> bool {
    flatbuffers::set_field::<i16>(Monster::VT_MANA, mana_, 150)
  }
  fn hp(&self) -> i16  {
    // yo
    flatbuffers::get_field::<i16>(Monster::VT_HP, 100)
  }
  fn mutate_hp(&mut self, hp_: i16) -> bool {
    flatbuffers::set_field::<i16>(Monster::VT_HP, hp_, 100)
  }
  fn name(&self) -> &flatbuffers::String  {
    // yo
    flatbuffers::get_pointer::<&flatbuffers::String>(Monster::VT_NAME)
  }
  fn mutable_name(&mut self) -> &mut flatbuffers::String  {
    /* TODO: are there non-reference choices here? */
    &mut flatbuffers::get_pointer::<&mut flatbuffers::String >(Monster::VT_NAME)
  }
  fn KeyCompareLessThan(&self, o: &Monster) -> bool {
    return *self.name() < *o.name();
  }
  fn KeyCompareWithValue(&self, val: &str) -> Ordering {
    Ordering::Equal
    // TODO(rw): self.name().cmp(val)
  }
  fn inventory(&self) -> &flatbuffers::Vector<u8>  {
    // yo
    flatbuffers::get_pointer::<&flatbuffers::Vector<u8>>(Monster::VT_INVENTORY)
  }
  fn mutable_inventory(&mut self) -> &mut flatbuffers::Vector<u8>  {
    /* TODO: are there non-reference choices here? */
    &mut flatbuffers::get_pointer::<&mut flatbuffers::Vector<u8> >(Monster::VT_INVENTORY)
  }
  fn color(&self) -> Color  {
    // yo
    EnumValuesColor[flatbuffers::get_field::<i8>(Monster::VT_COLOR, 8) as usize]
  }
  fn mutate_color(&mut self, color_: Color) -> bool {
    flatbuffers::set_field::<i8>(Monster::VT_COLOR, color_ as i8, 8)
  }
  fn test_type(&self) -> Any  {
    // yo
    EnumValuesAny[flatbuffers::get_field::<u8>(Monster::VT_TEST_TYPE, 0) as usize]
  }
  fn mutate_test_type(&mut self, test_type_: Any) -> bool {
    flatbuffers::set_field::<u8>(Monster::VT_TEST_TYPE, test_type_ as u8, 0)
  }
  fn test(&self) -> &flatbuffers::Void  {
    // yo
    flatbuffers::get_pointer::<&flatbuffers::Void>(Monster::VT_TEST)
  }
  // TODO(?) template<typename T> const T *test_as() const;
  // TODO: fn test_as_Monster() -> &Monster {
// TODO:     if test_type() == Any::Monster { static_cast::<&Monster>(test()) } else { nullptr }
// TODO:   }
  // TODO: fn test_as_TestSimpleTableWithEnum() -> &TestSimpleTableWithEnum {
// TODO:     if test_type() == Any::TestSimpleTableWithEnum { static_cast::<&TestSimpleTableWithEnum>(test()) } else { nullptr }
// TODO:   }
  // TODO: fn test_as_MyGame_Example2_Monster() -> &super::Example2::Monster {
// TODO:     if test_type() == Any::MyGame_Example2_Monster { static_cast::<&super::Example2::Monster>(test()) } else { nullptr }
// TODO:   }
  fn mutable_test(&mut self) -> &mut flatbuffers::Void  {
    /* TODO: are there non-reference choices here? */
    &mut flatbuffers::get_pointer::<&mut flatbuffers::Void >(Monster::VT_TEST)
  }
  fn test4(&self) -> &flatbuffers::Vector<&Test>  {
    // yo
    flatbuffers::get_pointer::<&flatbuffers::Vector<&Test>>(Monster::VT_TEST4)
  }
  fn mutable_test4(&mut self) -> &mut flatbuffers::Vector<&Test>  {
    /* TODO: are there non-reference choices here? */
    &mut flatbuffers::get_pointer::<&mut flatbuffers::Vector<&Test> >(Monster::VT_TEST4)
  }
  fn testarrayofstring(&self) -> &flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>  {
    // yo
    flatbuffers::get_pointer::<&flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>>(Monster::VT_TESTARRAYOFSTRING)
  }
  fn mutable_testarrayofstring(&mut self) -> &mut flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>  {
    /* TODO: are there non-reference choices here? */
    &mut flatbuffers::get_pointer::<&mut flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> >(Monster::VT_TESTARRAYOFSTRING)
  }
  /// an example documentation comment: this will end up in the generated code
  /// multiline too
  fn testarrayoftables(&self) -> &flatbuffers::Vector<flatbuffers::Offset<Monster>>  {
    // yo
    flatbuffers::get_pointer::<&flatbuffers::Vector<flatbuffers::Offset<Monster>>>(Monster::VT_TESTARRAYOFTABLES)
  }
  fn mutable_testarrayoftables(&mut self) -> &mut flatbuffers::Vector<flatbuffers::Offset<Monster>>  {
    /* TODO: are there non-reference choices here? */
    &mut flatbuffers::get_pointer::<&mut flatbuffers::Vector<flatbuffers::Offset<Monster>> >(Monster::VT_TESTARRAYOFTABLES)
  }
  fn enemy(&self) -> &Monster  {
    // yo
    flatbuffers::get_pointer::<&Monster>(Monster::VT_ENEMY)
  }
  fn mutable_enemy(&mut self) -> &mut Monster  {
    /* TODO: are there non-reference choices here? */
    &mut flatbuffers::get_pointer::<&mut Monster >(Monster::VT_ENEMY)
  }
  fn testnestedflatbuffer(&self) -> &flatbuffers::Vector<u8>  {
    // yo
    flatbuffers::get_pointer::<&flatbuffers::Vector<u8>>(Monster::VT_TESTNESTEDFLATBUFFER)
  }
  fn mutable_testnestedflatbuffer(&mut self) -> &mut flatbuffers::Vector<u8>  {
    /* TODO: are there non-reference choices here? */
    &mut flatbuffers::get_pointer::<&mut flatbuffers::Vector<u8> >(Monster::VT_TESTNESTEDFLATBUFFER)
  }
//TODO: mutable nested root
  fn testnestedflatbuffer_nested_root(&self) -> &Monster{
    unimplemented!()
    // TODO(rw): return flatbuffers::get_root::<Monster>(self.testnestedflatbuffer().Data());
  }
  fn testempty(&self) -> &Stat  {
    // yo
    flatbuffers::get_pointer::<&Stat>(Monster::VT_TESTEMPTY)
  }
  fn mutable_testempty(&mut self) -> &mut Stat  {
    /* TODO: are there non-reference choices here? */
    &mut flatbuffers::get_pointer::<&mut Stat >(Monster::VT_TESTEMPTY)
  }
  fn testbool(&self) -> bool  {
    // yo
    flatbuffers::get_field::<u8>(Monster::VT_TESTBOOL, 0) != 0
  }
  fn mutate_testbool(&mut self, testbool_: bool) -> bool {
    flatbuffers::set_field::<u8>(Monster::VT_TESTBOOL, testbool_ as u8, 0)
  }
  fn testhashs32_fnv1(&self) -> i32  {
    // yo
    flatbuffers::get_field::<i32>(Monster::VT_TESTHASHS32_FNV1, 0)
  }
  fn mutate_testhashs32_fnv1(&mut self, testhashs32_fnv1_: i32) -> bool {
    flatbuffers::set_field::<i32>(Monster::VT_TESTHASHS32_FNV1, testhashs32_fnv1_, 0)
  }
  fn testhashu32_fnv1(&self) -> u32  {
    // yo
    flatbuffers::get_field::<u32>(Monster::VT_TESTHASHU32_FNV1, 0)
  }
  fn mutate_testhashu32_fnv1(&mut self, testhashu32_fnv1_: u32) -> bool {
    flatbuffers::set_field::<u32>(Monster::VT_TESTHASHU32_FNV1, testhashu32_fnv1_, 0)
  }
  fn testhashs64_fnv1(&self) -> i64  {
    // yo
    flatbuffers::get_field::<i64>(Monster::VT_TESTHASHS64_FNV1, 0)
  }
  fn mutate_testhashs64_fnv1(&mut self, testhashs64_fnv1_: i64) -> bool {
    flatbuffers::set_field::<i64>(Monster::VT_TESTHASHS64_FNV1, testhashs64_fnv1_, 0)
  }
  fn testhashu64_fnv1(&self) -> u64  {
    // yo
    flatbuffers::get_field::<u64>(Monster::VT_TESTHASHU64_FNV1, 0)
  }
  fn mutate_testhashu64_fnv1(&mut self, testhashu64_fnv1_: u64) -> bool {
    flatbuffers::set_field::<u64>(Monster::VT_TESTHASHU64_FNV1, testhashu64_fnv1_, 0)
  }
  fn testhashs32_fnv1a(&self) -> i32  {
    // yo
    flatbuffers::get_field::<i32>(Monster::VT_TESTHASHS32_FNV1A, 0)
  }
  fn mutate_testhashs32_fnv1a(&mut self, testhashs32_fnv1a_: i32) -> bool {
    flatbuffers::set_field::<i32>(Monster::VT_TESTHASHS32_FNV1A, testhashs32_fnv1a_, 0)
  }
  fn testhashu32_fnv1a(&self) -> u32  {
    // yo
    flatbuffers::get_field::<u32>(Monster::VT_TESTHASHU32_FNV1A, 0)
  }
  fn mutate_testhashu32_fnv1a(&mut self, testhashu32_fnv1a_: u32) -> bool {
    flatbuffers::set_field::<u32>(Monster::VT_TESTHASHU32_FNV1A, testhashu32_fnv1a_, 0)
  }
  fn testhashs64_fnv1a(&self) -> i64  {
    // yo
    flatbuffers::get_field::<i64>(Monster::VT_TESTHASHS64_FNV1A, 0)
  }
  fn mutate_testhashs64_fnv1a(&mut self, testhashs64_fnv1a_: i64) -> bool {
    flatbuffers::set_field::<i64>(Monster::VT_TESTHASHS64_FNV1A, testhashs64_fnv1a_, 0)
  }
  fn testhashu64_fnv1a(&self) -> u64  {
    // yo
    flatbuffers::get_field::<u64>(Monster::VT_TESTHASHU64_FNV1A, 0)
  }
  fn mutate_testhashu64_fnv1a(&mut self, testhashu64_fnv1a_: u64) -> bool {
    flatbuffers::set_field::<u64>(Monster::VT_TESTHASHU64_FNV1A, testhashu64_fnv1a_, 0)
  }
  fn testarrayofbools(&self) -> &flatbuffers::Vector<u8>  {
    // yo
    flatbuffers::get_pointer::<&flatbuffers::Vector<u8>>(Monster::VT_TESTARRAYOFBOOLS)
  }
  fn mutable_testarrayofbools(&mut self) -> &mut flatbuffers::Vector<u8>  {
    /* TODO: are there non-reference choices here? */
    &mut flatbuffers::get_pointer::<&mut flatbuffers::Vector<u8> >(Monster::VT_TESTARRAYOFBOOLS)
  }
  fn testf(&self) -> f32  {
    // yo
    flatbuffers::get_field::<f32>(Monster::VT_TESTF, 3.14159)
  }
  fn mutate_testf(&mut self, testf_: f32) -> bool {
    flatbuffers::set_field::<f32>(Monster::VT_TESTF, testf_, 3.14159)
  }
  fn testf2(&self) -> f32  {
    // yo
    flatbuffers::get_field::<f32>(Monster::VT_TESTF2, 3.0)
  }
  fn mutate_testf2(&mut self, testf2_: f32) -> bool {
    flatbuffers::set_field::<f32>(Monster::VT_TESTF2, testf2_, 3.0)
  }
  fn testf3(&self) -> f32  {
    // yo
    flatbuffers::get_field::<f32>(Monster::VT_TESTF3, 0.0)
  }
  fn mutate_testf3(&mut self, testf3_: f32) -> bool {
    flatbuffers::set_field::<f32>(Monster::VT_TESTF3, testf3_, 0.0)
  }
  fn testarrayofstring2(&self) -> &flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>  {
    // yo
    flatbuffers::get_pointer::<&flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>>(Monster::VT_TESTARRAYOFSTRING2)
  }
  fn mutable_testarrayofstring2(&mut self) -> &mut flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>  {
    /* TODO: are there non-reference choices here? */
    &mut flatbuffers::get_pointer::<&mut flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> >(Monster::VT_TESTARRAYOFSTRING2)
  }
  fn testarrayofsortedstruct(&self) -> &flatbuffers::Vector<&Ability>  {
    // yo
    flatbuffers::get_pointer::<&flatbuffers::Vector<&Ability>>(Monster::VT_TESTARRAYOFSORTEDSTRUCT)
  }
  fn mutable_testarrayofsortedstruct(&mut self) -> &mut flatbuffers::Vector<&Ability>  {
    /* TODO: are there non-reference choices here? */
    &mut flatbuffers::get_pointer::<&mut flatbuffers::Vector<&Ability> >(Monster::VT_TESTARRAYOFSORTEDSTRUCT)
  }
  fn flex(&self) -> &flatbuffers::Vector<u8>  {
    // yo
    flatbuffers::get_pointer::<&flatbuffers::Vector<u8>>(Monster::VT_FLEX)
  }
  fn mutable_flex(&mut self) -> &mut flatbuffers::Vector<u8>  {
    /* TODO: are there non-reference choices here? */
    &mut flatbuffers::get_pointer::<&mut flatbuffers::Vector<u8> >(Monster::VT_FLEX)
  }
  fn test5(&self) -> &flatbuffers::Vector<&Test>  {
    // yo
    flatbuffers::get_pointer::<&flatbuffers::Vector<&Test>>(Monster::VT_TEST5)
  }
  fn mutable_test5(&mut self) -> &mut flatbuffers::Vector<&Test>  {
    /* TODO: are there non-reference choices here? */
    &mut flatbuffers::get_pointer::<&mut flatbuffers::Vector<&Test> >(Monster::VT_TEST5)
  }
  fn vector_of_longs(&self) -> &flatbuffers::Vector<i64>  {
    // yo
    flatbuffers::get_pointer::<&flatbuffers::Vector<i64>>(Monster::VT_VECTOR_OF_LONGS)
  }
  fn mutable_vector_of_longs(&mut self) -> &mut flatbuffers::Vector<i64>  {
    /* TODO: are there non-reference choices here? */
    &mut flatbuffers::get_pointer::<&mut flatbuffers::Vector<i64> >(Monster::VT_VECTOR_OF_LONGS)
  }
  fn vector_of_doubles(&self) -> &flatbuffers::Vector<f64>  {
    // yo
    flatbuffers::get_pointer::<&flatbuffers::Vector<f64>>(Monster::VT_VECTOR_OF_DOUBLES)
  }
  fn mutable_vector_of_doubles(&mut self) -> &mut flatbuffers::Vector<f64>  {
    /* TODO: are there non-reference choices here? */
    &mut flatbuffers::get_pointer::<&mut flatbuffers::Vector<f64> >(Monster::VT_VECTOR_OF_DOUBLES)
  }
  fn parent_namespace_test(&self) -> &super::InParentNamespace  {
    // yo
    flatbuffers::get_pointer::<&super::InParentNamespace>(Monster::VT_PARENT_NAMESPACE_TEST)
  }
  fn mutable_parent_namespace_test(&mut self) -> &mut super::InParentNamespace  {
    /* TODO: are there non-reference choices here? */
    &mut flatbuffers::get_pointer::<&mut super::InParentNamespace >(Monster::VT_PARENT_NAMESPACE_TEST)
  }
  fn Verify(&self, verifier: &flatbuffers::Verifier) -> bool {
    return flatbuffers::verify_table_start(verifier) &&
           flatbuffers::verify_field::<Vec3>(verifier, Monster::VT_POS) &&
           flatbuffers::verify_field::<i16>(verifier, Monster::VT_MANA) &&
           flatbuffers::verify_field::<i16>(verifier, Monster::VT_HP) &&
           flatbuffers::verify_offset_required(verifier, Monster::VT_NAME) &&
           verifier.verify(self.name()) &&
           flatbuffers::verify_offset(verifier, Monster::VT_INVENTORY) &&
           verifier.verify(self.inventory()) &&
           flatbuffers::verify_field::<i8>(verifier, Monster::VT_COLOR) &&
           flatbuffers::verify_field::<u8>(verifier, Monster::VT_TEST_TYPE) &&
           flatbuffers::verify_offset(verifier, Monster::VT_TEST) &&
           VerifyAny(verifier, self.test(), self.test_type()) &&
           flatbuffers::verify_offset(verifier, Monster::VT_TEST4) &&
           verifier.verify(self.test4()) &&
           flatbuffers::verify_offset(verifier, Monster::VT_TESTARRAYOFSTRING) &&
           verifier.verify(self.testarrayofstring()) &&
           verifier.verify_vector_of_strings(self.testarrayofstring()) &&
           flatbuffers::verify_offset(verifier, Monster::VT_TESTARRAYOFTABLES) &&
           verifier.verify(self.testarrayoftables()) &&
           verifier.verify_vector_of_tables(self.testarrayoftables()) &&
           flatbuffers::verify_offset(verifier, Monster::VT_ENEMY) &&
           verifier.verify_table(self.enemy()) &&
           flatbuffers::verify_offset(verifier, Monster::VT_TESTNESTEDFLATBUFFER) &&
           verifier.verify(self.testnestedflatbuffer()) &&
           flatbuffers::verify_offset(verifier, Monster::VT_TESTEMPTY) &&
           verifier.verify_table(self.testempty()) &&
           flatbuffers::verify_field::<u8>(verifier, Monster::VT_TESTBOOL) &&
           flatbuffers::verify_field::<i32>(verifier, Monster::VT_TESTHASHS32_FNV1) &&
           flatbuffers::verify_field::<u32>(verifier, Monster::VT_TESTHASHU32_FNV1) &&
           flatbuffers::verify_field::<i64>(verifier, Monster::VT_TESTHASHS64_FNV1) &&
           flatbuffers::verify_field::<u64>(verifier, Monster::VT_TESTHASHU64_FNV1) &&
           flatbuffers::verify_field::<i32>(verifier, Monster::VT_TESTHASHS32_FNV1A) &&
           flatbuffers::verify_field::<u32>(verifier, Monster::VT_TESTHASHU32_FNV1A) &&
           flatbuffers::verify_field::<i64>(verifier, Monster::VT_TESTHASHS64_FNV1A) &&
           flatbuffers::verify_field::<u64>(verifier, Monster::VT_TESTHASHU64_FNV1A) &&
           flatbuffers::verify_offset(verifier, Monster::VT_TESTARRAYOFBOOLS) &&
           verifier.verify(self.testarrayofbools()) &&
           flatbuffers::verify_field::<f32>(verifier, Monster::VT_TESTF) &&
           flatbuffers::verify_field::<f32>(verifier, Monster::VT_TESTF2) &&
           flatbuffers::verify_field::<f32>(verifier, Monster::VT_TESTF3) &&
           flatbuffers::verify_offset(verifier, Monster::VT_TESTARRAYOFSTRING2) &&
           verifier.verify(self.testarrayofstring2()) &&
           verifier.verify_vector_of_strings(self.testarrayofstring2()) &&
           flatbuffers::verify_offset(verifier, Monster::VT_TESTARRAYOFSORTEDSTRUCT) &&
           verifier.verify(self.testarrayofsortedstruct()) &&
           flatbuffers::verify_offset(verifier, Monster::VT_FLEX) &&
           verifier.verify(self.flex()) &&
           flatbuffers::verify_offset(verifier, Monster::VT_TEST5) &&
           verifier.verify(self.test5()) &&
           flatbuffers::verify_offset(verifier, Monster::VT_VECTOR_OF_LONGS) &&
           verifier.verify(self.vector_of_longs()) &&
           flatbuffers::verify_offset(verifier, Monster::VT_VECTOR_OF_DOUBLES) &&
           verifier.verify(self.vector_of_doubles()) &&
           flatbuffers::verify_offset(verifier, Monster::VT_PARENT_NAMESPACE_TEST) &&
           verifier.verify_table(self.parent_namespace_test()) &&
           verifier.end_table();
  }
}

//TODO: inject these functions into impl for type
//#[inline]
//fn Monster_MEMBER_test_as_X_Monster_X() -> &Monster {
//  return test_as_Monster();
//}
//
//TODO: inject these functions into impl for type
//#[inline]
//fn Monster_MEMBER_test_as_X_TestSimpleTableWithEnum_X() -> &TestSimpleTableWithEnum {
//  return test_as_TestSimpleTableWithEnum();
//}
//
//TODO: inject these functions into impl for type
//#[inline]
//fn Monster_MEMBER_test_as_X_super::Example2::Monster_X() -> &super::Example2::Monster {
//  return test_as_MyGame_Example2_Monster();
//}
//
pub struct MonsterBuilder<'a> {
  fbb_: &'a flatbuffers::FlatBufferBuilder,
  start_: flatbuffers::UOffsetT,
}
impl<'a> MonsterBuilder<'a> {
  fn add_pos(&mut self, pos: &Vec3) {
    self.fbb_.add_struct(Monster::VT_POS, pos);
  }
  fn add_mana(&mut self, mana: i16 ) {
    self.fbb_.add_element::<i16>(Monster::VT_MANA, mana, 150);
  }
  fn add_hp(&mut self, hp: i16 ) {
    self.fbb_.add_element::<i16>(Monster::VT_HP, hp, 100);
  }
  fn add_name(&mut self, name: flatbuffers::Offset<flatbuffers::String> ) {
    self.fbb_.add_offset(Monster::VT_NAME, name);
  }
  fn add_inventory(&mut self, inventory: flatbuffers::Offset<flatbuffers::Vector<u8>> ) {
    self.fbb_.add_offset(Monster::VT_INVENTORY, inventory);
  }
  fn add_color(&mut self, color: Color ) {
    self.fbb_.add_element::<i8>(Monster::VT_COLOR, color as i8, 8);
  }
  fn add_test_type(&mut self, test_type: Any ) {
    self.fbb_.add_element::<u8>(Monster::VT_TEST_TYPE, test_type as u8, 0);
  }
  fn add_test(&mut self, test: flatbuffers::Offset<flatbuffers::Void> ) {
    self.fbb_.add_offset(Monster::VT_TEST, test);
  }
  fn add_test4(&mut self, test4: flatbuffers::Offset<flatbuffers::Vector<&Test>> ) {
    self.fbb_.add_offset(Monster::VT_TEST4, test4);
  }
  fn add_testarrayofstring(&mut self, testarrayofstring: flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> ) {
    self.fbb_.add_offset(Monster::VT_TESTARRAYOFSTRING, testarrayofstring);
  }
  fn add_testarrayoftables(&mut self, testarrayoftables: flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Monster>>> ) {
    self.fbb_.add_offset(Monster::VT_TESTARRAYOFTABLES, testarrayoftables);
  }
  fn add_enemy(&mut self, enemy: flatbuffers::Offset<Monster> ) {
    self.fbb_.add_offset(Monster::VT_ENEMY, enemy);
  }
  fn add_testnestedflatbuffer(&mut self, testnestedflatbuffer: flatbuffers::Offset<flatbuffers::Vector<u8>> ) {
    self.fbb_.add_offset(Monster::VT_TESTNESTEDFLATBUFFER, testnestedflatbuffer);
  }
  fn add_testempty(&mut self, testempty: flatbuffers::Offset<Stat> ) {
    self.fbb_.add_offset(Monster::VT_TESTEMPTY, testempty);
  }
  fn add_testbool(&mut self, testbool: bool ) {
    self.fbb_.add_element::<u8>(Monster::VT_TESTBOOL, testbool as u8, 0);
  }
  fn add_testhashs32_fnv1(&mut self, testhashs32_fnv1: i32 ) {
    self.fbb_.add_element::<i32>(Monster::VT_TESTHASHS32_FNV1, testhashs32_fnv1, 0);
  }
  fn add_testhashu32_fnv1(&mut self, testhashu32_fnv1: u32 ) {
    self.fbb_.add_element::<u32>(Monster::VT_TESTHASHU32_FNV1, testhashu32_fnv1, 0);
  }
  fn add_testhashs64_fnv1(&mut self, testhashs64_fnv1: i64 ) {
    self.fbb_.add_element::<i64>(Monster::VT_TESTHASHS64_FNV1, testhashs64_fnv1, 0);
  }
  fn add_testhashu64_fnv1(&mut self, testhashu64_fnv1: u64 ) {
    self.fbb_.add_element::<u64>(Monster::VT_TESTHASHU64_FNV1, testhashu64_fnv1, 0);
  }
  fn add_testhashs32_fnv1a(&mut self, testhashs32_fnv1a: i32 ) {
    self.fbb_.add_element::<i32>(Monster::VT_TESTHASHS32_FNV1A, testhashs32_fnv1a, 0);
  }
  fn add_testhashu32_fnv1a(&mut self, testhashu32_fnv1a: u32 ) {
    self.fbb_.add_element::<u32>(Monster::VT_TESTHASHU32_FNV1A, testhashu32_fnv1a, 0);
  }
  fn add_testhashs64_fnv1a(&mut self, testhashs64_fnv1a: i64 ) {
    self.fbb_.add_element::<i64>(Monster::VT_TESTHASHS64_FNV1A, testhashs64_fnv1a, 0);
  }
  fn add_testhashu64_fnv1a(&mut self, testhashu64_fnv1a: u64 ) {
    self.fbb_.add_element::<u64>(Monster::VT_TESTHASHU64_FNV1A, testhashu64_fnv1a, 0);
  }
  fn add_testarrayofbools(&mut self, testarrayofbools: flatbuffers::Offset<flatbuffers::Vector<u8>> ) {
    self.fbb_.add_offset(Monster::VT_TESTARRAYOFBOOLS, testarrayofbools);
  }
  fn add_testf(&mut self, testf: f32 ) {
    self.fbb_.add_element::<f32>(Monster::VT_TESTF, testf, 3.14159);
  }
  fn add_testf2(&mut self, testf2: f32 ) {
    self.fbb_.add_element::<f32>(Monster::VT_TESTF2, testf2, 3.0);
  }
  fn add_testf3(&mut self, testf3: f32 ) {
    self.fbb_.add_element::<f32>(Monster::VT_TESTF3, testf3, 0.0);
  }
  fn add_testarrayofstring2(&mut self, testarrayofstring2: flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> ) {
    self.fbb_.add_offset(Monster::VT_TESTARRAYOFSTRING2, testarrayofstring2);
  }
  fn add_testarrayofsortedstruct(&mut self, testarrayofsortedstruct: flatbuffers::Offset<flatbuffers::Vector<&Ability>> ) {
    self.fbb_.add_offset(Monster::VT_TESTARRAYOFSORTEDSTRUCT, testarrayofsortedstruct);
  }
  fn add_flex(&mut self, flex: flatbuffers::Offset<flatbuffers::Vector<u8>> ) {
    self.fbb_.add_offset(Monster::VT_FLEX, flex);
  }
  fn add_test5(&mut self, test5: flatbuffers::Offset<flatbuffers::Vector<&Test>> ) {
    self.fbb_.add_offset(Monster::VT_TEST5, test5);
  }
  fn add_vector_of_longs(&mut self, vector_of_longs: flatbuffers::Offset<flatbuffers::Vector<i64>> ) {
    self.fbb_.add_offset(Monster::VT_VECTOR_OF_LONGS, vector_of_longs);
  }
  fn add_vector_of_doubles(&mut self, vector_of_doubles: flatbuffers::Offset<flatbuffers::Vector<f64>> ) {
    self.fbb_.add_offset(Monster::VT_VECTOR_OF_DOUBLES, vector_of_doubles);
  }
  fn add_parent_namespace_test(&mut self, parent_namespace_test: flatbuffers::Offset<super::InParentNamespace> ) {
    self.fbb_.add_offset(Monster::VT_PARENT_NAMESPACE_TEST, parent_namespace_test);
  }
  fn new(_fbb: &mut flatbuffers::FlatBufferBuilder) -> MonsterBuilder {
    MonsterBuilder {
      fbb_: _fbb,
      start_: _fbb.start_table(),
    }
  }
  // MonsterBuilder &operator=(const MonsterBuilder &);
  fn finish(&mut self) -> flatbuffers::Offset<Monster> {
    let end = self.fbb_.end_table(self.start_);
    let o = flatbuffers::Offset::<Monster>::new(end);
    self.fbb_.required(o, Monster::VT_NAME);
    o
  }
}

#[inline]
fn CreateMonster(
    _fbb: &mut flatbuffers::FlatBufferBuilder,
    pos: &Vec3 /* = 0 */,
    mana: i16  /* = 150 */,
    hp: i16  /* = 100 */,
    name: flatbuffers::Offset<flatbuffers::String>  /* = 0 */,
    inventory: flatbuffers::Offset<flatbuffers::Vector<u8>>  /* = 0 */,
    color: Color  /* = Color::Blue */,
    test_type: Any  /* = Any::NONE */,
    test: flatbuffers::Offset<flatbuffers::Void>  /* = 0 */,
    test4: flatbuffers::Offset<flatbuffers::Vector<&Test>>  /* = 0 */,
    testarrayofstring: flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>>  /* = 0 */,
    testarrayoftables: flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Monster>>>  /* = 0 */,
    enemy: flatbuffers::Offset<Monster>  /* = 0 */,
    testnestedflatbuffer: flatbuffers::Offset<flatbuffers::Vector<u8>>  /* = 0 */,
    testempty: flatbuffers::Offset<Stat>  /* = 0 */,
    testbool: bool  /* = false */,
    testhashs32_fnv1: i32  /* = 0 */,
    testhashu32_fnv1: u32  /* = 0 */,
    testhashs64_fnv1: i64  /* = 0 */,
    testhashu64_fnv1: u64  /* = 0 */,
    testhashs32_fnv1a: i32  /* = 0 */,
    testhashu32_fnv1a: u32  /* = 0 */,
    testhashs64_fnv1a: i64  /* = 0 */,
    testhashu64_fnv1a: u64  /* = 0 */,
    testarrayofbools: flatbuffers::Offset<flatbuffers::Vector<u8>>  /* = 0 */,
    testf: f32  /* = 3.14159 */,
    testf2: f32  /* = 3.0 */,
    testf3: f32  /* = 0.0 */,
    testarrayofstring2: flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>>  /* = 0 */,
    testarrayofsortedstruct: flatbuffers::Offset<flatbuffers::Vector<&Ability>>  /* = 0 */,
    flex: flatbuffers::Offset<flatbuffers::Vector<u8>>  /* = 0 */,
    test5: flatbuffers::Offset<flatbuffers::Vector<&Test>>  /* = 0 */,
    vector_of_longs: flatbuffers::Offset<flatbuffers::Vector<i64>>  /* = 0 */,
    vector_of_doubles: flatbuffers::Offset<flatbuffers::Vector<f64>>  /* = 0 */,
    parent_namespace_test: flatbuffers::Offset<super::InParentNamespace>  /* = 0 */) -> flatbuffers::Offset<Monster> {
  let mut builder = MonsterBuilder::new(_fbb);
  builder.add_testhashu64_fnv1a(testhashu64_fnv1a);
  builder.add_testhashs64_fnv1a(testhashs64_fnv1a);
  builder.add_testhashu64_fnv1(testhashu64_fnv1);
  builder.add_testhashs64_fnv1(testhashs64_fnv1);
  builder.add_parent_namespace_test(parent_namespace_test);
  builder.add_vector_of_doubles(vector_of_doubles);
  builder.add_vector_of_longs(vector_of_longs);
  builder.add_test5(test5);
  builder.add_flex(flex);
  builder.add_testarrayofsortedstruct(testarrayofsortedstruct);
  builder.add_testarrayofstring2(testarrayofstring2);
  builder.add_testf3(testf3);
  builder.add_testf2(testf2);
  builder.add_testf(testf);
  builder.add_testarrayofbools(testarrayofbools);
  builder.add_testhashu32_fnv1a(testhashu32_fnv1a);
  builder.add_testhashs32_fnv1a(testhashs32_fnv1a);
  builder.add_testhashu32_fnv1(testhashu32_fnv1);
  builder.add_testhashs32_fnv1(testhashs32_fnv1);
  builder.add_testempty(testempty);
  builder.add_testnestedflatbuffer(testnestedflatbuffer);
  builder.add_enemy(enemy);
  builder.add_testarrayoftables(testarrayoftables);
  builder.add_testarrayofstring(testarrayofstring);
  builder.add_test4(test4);
  builder.add_test(test);
  builder.add_inventory(inventory);
  builder.add_name(name);
  builder.add_pos(pos);
  builder.add_hp(hp);
  builder.add_mana(mana);
  builder.add_testbool(testbool);
  builder.add_test_type(test_type);
  builder.add_color(color);
  builder.finish()
}

#[inline]
fn CreateMonsterDirect(
    _fbb: &mut flatbuffers::FlatBufferBuilder,
    pos: &Vec3 /* = 0 */,
    mana: i16  /* = 150 */,
    hp: i16  /* = 100 */,
    name: Option<&str> /* = nullptr */,
    inventory: Option<Vec<u8>> /* = nullptr */,
    color: Color  /* = Color::Blue */,
    test_type: Any  /* = Any::NONE */,
    test: flatbuffers::Offset<flatbuffers::Void>  /* = 0 */,
    test4: Option<Vec<Test>> /* = nullptr */,
    testarrayofstring: Option<Vec<flatbuffers::Offset<flatbuffers::String>>> /* = nullptr */,
    testarrayoftables: Option<Vec<flatbuffers::Offset<Monster>>> /* = nullptr */,
    enemy: flatbuffers::Offset<Monster>  /* = 0 */,
    testnestedflatbuffer: Option<Vec<u8>> /* = nullptr */,
    testempty: flatbuffers::Offset<Stat>  /* = 0 */,
    testbool: bool  /* = false */,
    testhashs32_fnv1: i32  /* = 0 */,
    testhashu32_fnv1: u32  /* = 0 */,
    testhashs64_fnv1: i64  /* = 0 */,
    testhashu64_fnv1: u64  /* = 0 */,
    testhashs32_fnv1a: i32  /* = 0 */,
    testhashu32_fnv1a: u32  /* = 0 */,
    testhashs64_fnv1a: i64  /* = 0 */,
    testhashu64_fnv1a: u64  /* = 0 */,
    testarrayofbools: Option<Vec<u8>> /* = nullptr */,
    testf: f32  /* = 3.14159 */,
    testf2: f32  /* = 3.0 */,
    testf3: f32  /* = 0.0 */,
    testarrayofstring2: Option<Vec<flatbuffers::Offset<flatbuffers::String>>> /* = nullptr */,
    testarrayofsortedstruct: Option<Vec<Ability>> /* = nullptr */,
    flex: Option<Vec<u8>> /* = nullptr */,
    test5: Option<Vec<Test>> /* = nullptr */,
    vector_of_longs: Option<Vec<i64>> /* = nullptr */,
    vector_of_doubles: Option<Vec<f64>> /* = nullptr */,
    parent_namespace_test: flatbuffers::Offset<super::InParentNamespace>  /* = 0 */) -> flatbuffers::Offset<Monster> {
  return CreateMonster(
      _fbb,
      pos,
      mana,
      hp,
      if let Some(x) = name { _fbb.create_string(x) } else { flatbuffers::Offset::new(0) },
      if let Some(x) = inventory { _fbb.create_vector::<u8>(&x) } else { flatbuffers::Offset::new(0) },
      color,
      test_type,
      test,
      if let Some(x) = test4 { _fbb.create_vector_of_structs::<Test>(&x) } else { flatbuffers::Offset::new(0) },
      if let Some(x) = testarrayofstring { _fbb.create_vector::<flatbuffers::Offset<flatbuffers::String>>(&x) } else { flatbuffers::Offset::new(0) },
      if let Some(x) = testarrayoftables { _fbb.create_vector::<flatbuffers::Offset<Monster>>(&x) } else { flatbuffers::Offset::new(0) },
      enemy,
      if let Some(x) = testnestedflatbuffer { _fbb.create_vector::<u8>(&x) } else { flatbuffers::Offset::new(0) },
      testempty,
      testbool,
      testhashs32_fnv1,
      testhashu32_fnv1,
      testhashs64_fnv1,
      testhashu64_fnv1,
      testhashs32_fnv1a,
      testhashu32_fnv1a,
      testhashs64_fnv1a,
      testhashu64_fnv1a,
      if let Some(x) = testarrayofbools { _fbb.create_vector::<u8>(&x) } else { flatbuffers::Offset::new(0) },
      testf,
      testf2,
      testf3,
      if let Some(x) = testarrayofstring2 { _fbb.create_vector::<flatbuffers::Offset<flatbuffers::String>>(&x) } else { flatbuffers::Offset::new(0) },
      if let Some(x) = testarrayofsortedstruct { _fbb.create_vector_of_structs::<Ability>(&x) } else { flatbuffers::Offset::new(0) },
      if let Some(x) = flex { _fbb.create_vector::<u8>(&x) } else { flatbuffers::Offset::new(0) },
      if let Some(x) = test5 { _fbb.create_vector_of_structs::<Test>(&x) } else { flatbuffers::Offset::new(0) },
      if let Some(x) = vector_of_longs { _fbb.create_vector::<i64>(&x) } else { flatbuffers::Offset::new(0) },
      if let Some(x) = vector_of_doubles { _fbb.create_vector::<f64>(&x) } else { flatbuffers::Offset::new(0) },
      parent_namespace_test);
}

pub struct TypeAliases {}
impl flatbuffers::Table for TypeAliases {}
impl TypeAliases /* private flatbuffers::Table */ {
    const VT_I8_: isize = 4;
    const VT_U8_: isize = 6;
    const VT_I16_: isize = 8;
    const VT_U16_: isize = 10;
    const VT_I32_: isize = 12;
    const VT_U32_: isize = 14;
    const VT_I64_: isize = 16;
    const VT_U64_: isize = 18;
    const VT_F32_: isize = 20;
    const VT_F64_: isize = 22;
    const VT_V8: isize = 24;
    const VT_VF64: isize = 26;

  fn i8_(&self) -> i8  {
    // yo
    flatbuffers::get_field::<i8>(TypeAliases::VT_I8_, 0)
  }
  fn mutate_i8_(&mut self, i8__: i8) -> bool {
    flatbuffers::set_field::<i8>(TypeAliases::VT_I8_, i8__, 0)
  }
  fn u8_(&self) -> u8  {
    // yo
    flatbuffers::get_field::<u8>(TypeAliases::VT_U8_, 0)
  }
  fn mutate_u8_(&mut self, u8__: u8) -> bool {
    flatbuffers::set_field::<u8>(TypeAliases::VT_U8_, u8__, 0)
  }
  fn i16_(&self) -> i16  {
    // yo
    flatbuffers::get_field::<i16>(TypeAliases::VT_I16_, 0)
  }
  fn mutate_i16_(&mut self, i16__: i16) -> bool {
    flatbuffers::set_field::<i16>(TypeAliases::VT_I16_, i16__, 0)
  }
  fn u16_(&self) -> u16  {
    // yo
    flatbuffers::get_field::<u16>(TypeAliases::VT_U16_, 0)
  }
  fn mutate_u16_(&mut self, u16__: u16) -> bool {
    flatbuffers::set_field::<u16>(TypeAliases::VT_U16_, u16__, 0)
  }
  fn i32_(&self) -> i32  {
    // yo
    flatbuffers::get_field::<i32>(TypeAliases::VT_I32_, 0)
  }
  fn mutate_i32_(&mut self, i32__: i32) -> bool {
    flatbuffers::set_field::<i32>(TypeAliases::VT_I32_, i32__, 0)
  }
  fn u32_(&self) -> u32  {
    // yo
    flatbuffers::get_field::<u32>(TypeAliases::VT_U32_, 0)
  }
  fn mutate_u32_(&mut self, u32__: u32) -> bool {
    flatbuffers::set_field::<u32>(TypeAliases::VT_U32_, u32__, 0)
  }
  fn i64_(&self) -> i64  {
    // yo
    flatbuffers::get_field::<i64>(TypeAliases::VT_I64_, 0)
  }
  fn mutate_i64_(&mut self, i64__: i64) -> bool {
    flatbuffers::set_field::<i64>(TypeAliases::VT_I64_, i64__, 0)
  }
  fn u64_(&self) -> u64  {
    // yo
    flatbuffers::get_field::<u64>(TypeAliases::VT_U64_, 0)
  }
  fn mutate_u64_(&mut self, u64__: u64) -> bool {
    flatbuffers::set_field::<u64>(TypeAliases::VT_U64_, u64__, 0)
  }
  fn f32_(&self) -> f32  {
    // yo
    flatbuffers::get_field::<f32>(TypeAliases::VT_F32_, 0.0)
  }
  fn mutate_f32_(&mut self, f32__: f32) -> bool {
    flatbuffers::set_field::<f32>(TypeAliases::VT_F32_, f32__, 0.0)
  }
  fn f64_(&self) -> f64  {
    // yo
    flatbuffers::get_field::<f64>(TypeAliases::VT_F64_, 0.0)
  }
  fn mutate_f64_(&mut self, f64__: f64) -> bool {
    flatbuffers::set_field::<f64>(TypeAliases::VT_F64_, f64__, 0.0)
  }
  fn v8(&self) -> &flatbuffers::Vector<i8>  {
    // yo
    flatbuffers::get_pointer::<&flatbuffers::Vector<i8>>(TypeAliases::VT_V8)
  }
  fn mutable_v8(&mut self) -> &mut flatbuffers::Vector<i8>  {
    /* TODO: are there non-reference choices here? */
    &mut flatbuffers::get_pointer::<&mut flatbuffers::Vector<i8> >(TypeAliases::VT_V8)
  }
  fn vf64(&self) -> &flatbuffers::Vector<f64>  {
    // yo
    flatbuffers::get_pointer::<&flatbuffers::Vector<f64>>(TypeAliases::VT_VF64)
  }
  fn mutable_vf64(&mut self) -> &mut flatbuffers::Vector<f64>  {
    /* TODO: are there non-reference choices here? */
    &mut flatbuffers::get_pointer::<&mut flatbuffers::Vector<f64> >(TypeAliases::VT_VF64)
  }
  fn Verify(&self, verifier: &flatbuffers::Verifier) -> bool {
    return flatbuffers::verify_table_start(verifier) &&
           flatbuffers::verify_field::<i8>(verifier, TypeAliases::VT_I8_) &&
           flatbuffers::verify_field::<u8>(verifier, TypeAliases::VT_U8_) &&
           flatbuffers::verify_field::<i16>(verifier, TypeAliases::VT_I16_) &&
           flatbuffers::verify_field::<u16>(verifier, TypeAliases::VT_U16_) &&
           flatbuffers::verify_field::<i32>(verifier, TypeAliases::VT_I32_) &&
           flatbuffers::verify_field::<u32>(verifier, TypeAliases::VT_U32_) &&
           flatbuffers::verify_field::<i64>(verifier, TypeAliases::VT_I64_) &&
           flatbuffers::verify_field::<u64>(verifier, TypeAliases::VT_U64_) &&
           flatbuffers::verify_field::<f32>(verifier, TypeAliases::VT_F32_) &&
           flatbuffers::verify_field::<f64>(verifier, TypeAliases::VT_F64_) &&
           flatbuffers::verify_offset(verifier, TypeAliases::VT_V8) &&
           verifier.verify(self.v8()) &&
           flatbuffers::verify_offset(verifier, TypeAliases::VT_VF64) &&
           verifier.verify(self.vf64()) &&
           verifier.end_table();
  }
}

pub struct TypeAliasesBuilder<'a> {
  fbb_: &'a flatbuffers::FlatBufferBuilder,
  start_: flatbuffers::UOffsetT,
}
impl<'a> TypeAliasesBuilder<'a> {
  fn add_i8_(&mut self, i8_: i8 ) {
    self.fbb_.add_element::<i8>(TypeAliases::VT_I8_, i8_, 0);
  }
  fn add_u8_(&mut self, u8_: u8 ) {
    self.fbb_.add_element::<u8>(TypeAliases::VT_U8_, u8_, 0);
  }
  fn add_i16_(&mut self, i16_: i16 ) {
    self.fbb_.add_element::<i16>(TypeAliases::VT_I16_, i16_, 0);
  }
  fn add_u16_(&mut self, u16_: u16 ) {
    self.fbb_.add_element::<u16>(TypeAliases::VT_U16_, u16_, 0);
  }
  fn add_i32_(&mut self, i32_: i32 ) {
    self.fbb_.add_element::<i32>(TypeAliases::VT_I32_, i32_, 0);
  }
  fn add_u32_(&mut self, u32_: u32 ) {
    self.fbb_.add_element::<u32>(TypeAliases::VT_U32_, u32_, 0);
  }
  fn add_i64_(&mut self, i64_: i64 ) {
    self.fbb_.add_element::<i64>(TypeAliases::VT_I64_, i64_, 0);
  }
  fn add_u64_(&mut self, u64_: u64 ) {
    self.fbb_.add_element::<u64>(TypeAliases::VT_U64_, u64_, 0);
  }
  fn add_f32_(&mut self, f32_: f32 ) {
    self.fbb_.add_element::<f32>(TypeAliases::VT_F32_, f32_, 0.0);
  }
  fn add_f64_(&mut self, f64_: f64 ) {
    self.fbb_.add_element::<f64>(TypeAliases::VT_F64_, f64_, 0.0);
  }
  fn add_v8(&mut self, v8: flatbuffers::Offset<flatbuffers::Vector<i8>> ) {
    self.fbb_.add_offset(TypeAliases::VT_V8, v8);
  }
  fn add_vf64(&mut self, vf64: flatbuffers::Offset<flatbuffers::Vector<f64>> ) {
    self.fbb_.add_offset(TypeAliases::VT_VF64, vf64);
  }
  fn new(_fbb: &mut flatbuffers::FlatBufferBuilder) -> TypeAliasesBuilder {
    TypeAliasesBuilder {
      fbb_: _fbb,
      start_: _fbb.start_table(),
    }
  }
  // TypeAliasesBuilder &operator=(const TypeAliasesBuilder &);
  fn finish(&mut self) -> flatbuffers::Offset<TypeAliases> {
    let end = self.fbb_.end_table(self.start_);
    let o = flatbuffers::Offset::<TypeAliases>::new(end);
    o
  }
}

#[inline]
fn CreateTypeAliases(
    _fbb: &mut flatbuffers::FlatBufferBuilder,
    i8_: i8  /* = 0 */,
    u8_: u8  /* = 0 */,
    i16_: i16  /* = 0 */,
    u16_: u16  /* = 0 */,
    i32_: i32  /* = 0 */,
    u32_: u32  /* = 0 */,
    i64_: i64  /* = 0 */,
    u64_: u64  /* = 0 */,
    f32_: f32  /* = 0.0 */,
    f64_: f64  /* = 0.0 */,
    v8: flatbuffers::Offset<flatbuffers::Vector<i8>>  /* = 0 */,
    vf64: flatbuffers::Offset<flatbuffers::Vector<f64>>  /* = 0 */) -> flatbuffers::Offset<TypeAliases> {
  let mut builder = TypeAliasesBuilder::new(_fbb);
  builder.add_f64_(f64_);
  builder.add_u64_(u64_);
  builder.add_i64_(i64_);
  builder.add_vf64(vf64);
  builder.add_v8(v8);
  builder.add_f32_(f32_);
  builder.add_u32_(u32_);
  builder.add_i32_(i32_);
  builder.add_u16_(u16_);
  builder.add_i16_(i16_);
  builder.add_u8_(u8_);
  builder.add_i8_(i8_);
  builder.finish()
}

#[inline]
fn CreateTypeAliasesDirect(
    _fbb: &mut flatbuffers::FlatBufferBuilder,
    i8_: i8  /* = 0 */,
    u8_: u8  /* = 0 */,
    i16_: i16  /* = 0 */,
    u16_: u16  /* = 0 */,
    i32_: i32  /* = 0 */,
    u32_: u32  /* = 0 */,
    i64_: i64  /* = 0 */,
    u64_: u64  /* = 0 */,
    f32_: f32  /* = 0.0 */,
    f64_: f64  /* = 0.0 */,
    v8: Option<Vec<i8>> /* = nullptr */,
    vf64: Option<Vec<f64>> /* = nullptr */) -> flatbuffers::Offset<TypeAliases> {
  return CreateTypeAliases(
      _fbb,
      i8_,
      u8_,
      i16_,
      u16_,
      i32_,
      u32_,
      i64_,
      u64_,
      f32_,
      f64_,
      if let Some(x) = v8 { _fbb.create_vector::<i8>(&x) } else { flatbuffers::Offset::new(0) },
      if let Some(x) = vf64 { _fbb.create_vector::<f64>(&x) } else { flatbuffers::Offset::new(0) });
}

#[inline]
fn VerifyAny(verifier: &flatbuffers::Verifier, obj: &[u8], type_: Any) -> bool {
  match type_ {
    Any::NONE => {
      return true;
    }
    Any::Monster => {

      if obj.len() != mem::size_of::<Monster>() {
          return false;
      }
      let x: &Monster = unsafe {
        &*(obj.as_ptr() as *const Monster)
      };
      return verifier.verify_table::<&Monster>(x);
    }
    Any::TestSimpleTableWithEnum => {

      if obj.len() != mem::size_of::<TestSimpleTableWithEnum>() {
          return false;
      }
      let x: &TestSimpleTableWithEnum = unsafe {
        &*(obj.as_ptr() as *const TestSimpleTableWithEnum)
      };
      return verifier.verify_table::<&TestSimpleTableWithEnum>(x);
    }
    Any::MyGame_Example2_Monster => {

      if obj.len() != mem::size_of::<super::Example2::Monster>() {
          return false;
      }
      let x: &super::Example2::Monster = unsafe {
        &*(obj.as_ptr() as *const super::Example2::Monster)
      };
      return verifier.verify_table::<&super::Example2::Monster>(x);
    }
    _ => { return false; }
  }
}

#[inline]
fn VerifyAnyVector(verifier: &flatbuffers::Verifier, values: &[flatbuffers::Offset<flatbuffers::Void>], types: &[u8]) -> bool {
  //if values.len() == 0 || types.len() == 0 {
  //  return values.len() == types.len();
  //}
  if values.len() != types.len() { return false; }
  for i in (0 as flatbuffers::UOffsetT)..values.len() {
    //if !VerifyAny(
    //    verifier,  values.Get(i), types.GetEnum::<Any>(i)) {
    //  return false;
    //}
  }
  return true;
}

#[inline]
fn ColorTypeTable() -> /*&mut?*/flatbuffers::TypeTable {
  return flatbuffers::TypeTable{};
  /* disable type table for now
  static flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_CHAR, 0, 0 },
    { flatbuffers::ET_CHAR, 0, 0 },
    { flatbuffers::ET_CHAR, 0, 0 }
  };
  static flatbuffers::TypeFunction type_refs[] = {
    ColorTypeTable
  };
  static const int32_t values[] = { 1, 2, 8 };
  static const char *names[] = {
    "Red",
    "Green",
    "Blue"
  };
  static flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 3, type_codes, type_refs, values, names
  };
  return &tt;
  */
}

#[inline]
fn AnyTypeTable() -> /*&mut?*/flatbuffers::TypeTable {
  return flatbuffers::TypeTable{};
  /* disable type table for now
  static flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_SEQUENCE, 0, -1 },
    { flatbuffers::ET_SEQUENCE, 0, 0 },
    { flatbuffers::ET_SEQUENCE, 0, 1 },
    { flatbuffers::ET_SEQUENCE, 0, 2 }
  };
  static flatbuffers::TypeFunction type_refs[] = {
    MonsterTypeTable,
    TestSimpleTableWithEnumTypeTable,
    MyGame::Example2::MonsterTypeTable
  };
  static const char *names[] = {
    "NONE",
    "Monster",
    "TestSimpleTableWithEnum",
    "MyGame_Example2_Monster"
  };
  static flatbuffers::TypeTable tt = {
    flatbuffers::ST_UNION, 4, type_codes, type_refs, nullptr, names
  };
  return &tt;
  */
}

#[inline]
fn TestTypeTable() -> /*&mut?*/flatbuffers::TypeTable {
  return flatbuffers::TypeTable{};
  /* disable type table for now
  static flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_SHORT, 0, -1 },
    { flatbuffers::ET_CHAR, 0, -1 }
  };
  static const int32_t values[] = { 0, 2, 4 };
  static const char *names[] = {
    "a",
    "b"
  };
  static flatbuffers::TypeTable tt = {
    flatbuffers::ST_STRUCT, 2, type_codes, nullptr, values, names
  };
  return &tt;
  */
}

#[inline]
fn TestSimpleTableWithEnumTypeTable() -> /*&mut?*/flatbuffers::TypeTable {
  return flatbuffers::TypeTable{};
  /* disable type table for now
  static flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_CHAR, 0, 0 }
  };
  static flatbuffers::TypeFunction type_refs[] = {
    ColorTypeTable
  };
  static const char *names[] = {
    "color"
  };
  static flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 1, type_codes, type_refs, nullptr, names
  };
  return &tt;
  */
}

#[inline]
fn Vec3TypeTable() -> /*&mut?*/flatbuffers::TypeTable {
  return flatbuffers::TypeTable{};
  /* disable type table for now
  static flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_FLOAT, 0, -1 },
    { flatbuffers::ET_FLOAT, 0, -1 },
    { flatbuffers::ET_FLOAT, 0, -1 },
    { flatbuffers::ET_DOUBLE, 0, -1 },
    { flatbuffers::ET_CHAR, 0, 0 },
    { flatbuffers::ET_SEQUENCE, 0, 1 }
  };
  static flatbuffers::TypeFunction type_refs[] = {
    ColorTypeTable,
    TestTypeTable
  };
  static const int32_t values[] = { 0, 4, 8, 16, 24, 26, 32 };
  static const char *names[] = {
    "x",
    "y",
    "z",
    "test1",
    "test2",
    "test3"
  };
  static flatbuffers::TypeTable tt = {
    flatbuffers::ST_STRUCT, 6, type_codes, type_refs, values, names
  };
  return &tt;
  */
}

#[inline]
fn AbilityTypeTable() -> /*&mut?*/flatbuffers::TypeTable {
  return flatbuffers::TypeTable{};
  /* disable type table for now
  static flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UINT, 0, -1 },
    { flatbuffers::ET_UINT, 0, -1 }
  };
  static const int32_t values[] = { 0, 4, 8 };
  static const char *names[] = {
    "id",
    "distance"
  };
  static flatbuffers::TypeTable tt = {
    flatbuffers::ST_STRUCT, 2, type_codes, nullptr, values, names
  };
  return &tt;
  */
}

#[inline]
fn StatTypeTable() -> /*&mut?*/flatbuffers::TypeTable {
  return flatbuffers::TypeTable{};
  /* disable type table for now
  static flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_STRING, 0, -1 },
    { flatbuffers::ET_LONG, 0, -1 },
    { flatbuffers::ET_USHORT, 0, -1 }
  };
  static const char *names[] = {
    "id",
    "val",
    "count"
  };
  static flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 3, type_codes, nullptr, nullptr, names
  };
  return &tt;
  */
}

#[inline]
fn MonsterTypeTable() -> /*&mut?*/flatbuffers::TypeTable {
  return flatbuffers::TypeTable{};
  /* disable type table for now
  static flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_SEQUENCE, 0, 0 },
    { flatbuffers::ET_SHORT, 0, -1 },
    { flatbuffers::ET_SHORT, 0, -1 },
    { flatbuffers::ET_STRING, 0, -1 },
    { flatbuffers::ET_BOOL, 0, -1 },
    { flatbuffers::ET_UCHAR, 1, -1 },
    { flatbuffers::ET_CHAR, 0, 1 },
    { flatbuffers::ET_UTYPE, 0, 2 },
    { flatbuffers::ET_SEQUENCE, 0, 2 },
    { flatbuffers::ET_SEQUENCE, 1, 3 },
    { flatbuffers::ET_STRING, 1, -1 },
    { flatbuffers::ET_SEQUENCE, 1, 4 },
    { flatbuffers::ET_SEQUENCE, 0, 4 },
    { flatbuffers::ET_UCHAR, 1, -1 },
    { flatbuffers::ET_SEQUENCE, 0, 5 },
    { flatbuffers::ET_BOOL, 0, -1 },
    { flatbuffers::ET_INT, 0, -1 },
    { flatbuffers::ET_UINT, 0, -1 },
    { flatbuffers::ET_LONG, 0, -1 },
    { flatbuffers::ET_ULONG, 0, -1 },
    { flatbuffers::ET_INT, 0, -1 },
    { flatbuffers::ET_UINT, 0, -1 },
    { flatbuffers::ET_LONG, 0, -1 },
    { flatbuffers::ET_ULONG, 0, -1 },
    { flatbuffers::ET_BOOL, 1, -1 },
    { flatbuffers::ET_FLOAT, 0, -1 },
    { flatbuffers::ET_FLOAT, 0, -1 },
    { flatbuffers::ET_FLOAT, 0, -1 },
    { flatbuffers::ET_STRING, 1, -1 },
    { flatbuffers::ET_SEQUENCE, 1, 6 },
    { flatbuffers::ET_UCHAR, 1, -1 },
    { flatbuffers::ET_SEQUENCE, 1, 3 },
    { flatbuffers::ET_LONG, 1, -1 },
    { flatbuffers::ET_DOUBLE, 1, -1 },
    { flatbuffers::ET_SEQUENCE, 0, 7 }
  };
  static flatbuffers::TypeFunction type_refs[] = {
    Vec3TypeTable,
    ColorTypeTable,
    AnyTypeTable,
    TestTypeTable,
    MonsterTypeTable,
    StatTypeTable,
    AbilityTypeTable,
    MyGame::InParentNamespaceTypeTable
  };
  static const char *names[] = {
    "pos",
    "mana",
    "hp",
    "name",
    "friendly",
    "inventory",
    "color",
    "test_type",
    "test",
    "test4",
    "testarrayofstring",
    "testarrayoftables",
    "enemy",
    "testnestedflatbuffer",
    "testempty",
    "testbool",
    "testhashs32_fnv1",
    "testhashu32_fnv1",
    "testhashs64_fnv1",
    "testhashu64_fnv1",
    "testhashs32_fnv1a",
    "testhashu32_fnv1a",
    "testhashs64_fnv1a",
    "testhashu64_fnv1a",
    "testarrayofbools",
    "testf",
    "testf2",
    "testf3",
    "testarrayofstring2",
    "testarrayofsortedstruct",
    "flex",
    "test5",
    "vector_of_longs",
    "vector_of_doubles",
    "parent_namespace_test"
  };
  static flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 35, type_codes, type_refs, nullptr, names
  };
  return &tt;
  */
}

#[inline]
fn TypeAliasesTypeTable() -> /*&mut?*/flatbuffers::TypeTable {
  return flatbuffers::TypeTable{};
  /* disable type table for now
  static flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_CHAR, 0, -1 },
    { flatbuffers::ET_UCHAR, 0, -1 },
    { flatbuffers::ET_SHORT, 0, -1 },
    { flatbuffers::ET_USHORT, 0, -1 },
    { flatbuffers::ET_INT, 0, -1 },
    { flatbuffers::ET_UINT, 0, -1 },
    { flatbuffers::ET_LONG, 0, -1 },
    { flatbuffers::ET_ULONG, 0, -1 },
    { flatbuffers::ET_FLOAT, 0, -1 },
    { flatbuffers::ET_DOUBLE, 0, -1 },
    { flatbuffers::ET_CHAR, 1, -1 },
    { flatbuffers::ET_DOUBLE, 1, -1 }
  };
  static const char *names[] = {
    "i8_",
    "u8_",
    "i16_",
    "u16_",
    "i32_",
    "u32_",
    "i64_",
    "u64_",
    "f32_",
    "f64_",
    "v8",
    "vf64"
  };
  static flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 12, type_codes, nullptr, nullptr, names
  };
  return &tt;
  */
}

#[inline]
fn GetMonster(buf: &[u8]) -> &Monster  {
  return flatbuffers::get_root::<&Monster>(buf);
}

#[inline]
fn GetMutableMonster(buf: &[u8]) -> &Monster {
  return flatbuffers::get_mutable_root::<&Monster>(buf);
}

#[inline]
fn MonsterIdentifier() -> &'static str {
  return "MONS";
}

#[inline]
fn MonsterBufferHasIdentifier(buf: &Vec<u8>) -> bool {
  return flatbuffers::buffer_has_identifier(
      buf, MonsterIdentifier());
}

#[inline]
fn VerifyMonsterBuffer(
    verifier: &flatbuffers::Verifier) -> bool {
  return verifier.verify_buffer::<Monster>(MonsterIdentifier());
}

#[inline]
fn MonsterExtension() -> &'static str {
  return "mon";
}

#[inline]
fn FinishMonsterBuffer(
    fbb: &mut flatbuffers::FlatBufferBuilder,
    root: flatbuffers::Offset<Monster>) {
  fbb.finish_with_identifier(root, MonsterIdentifier());
}

}  // pub mod Example
}  // pub mod MyGame

