// automatically generated by the FlatBuffers compiler, do not modify



pub mod MyGame {
  #[allow(unused_imports)]
  use std::mem;
  #[allow(unused_imports)]
  use std::marker::PhantomData;
  #[allow(unused_imports)]
  #[allow(unreachable_code)]
  extern crate flatbuffers;
  #[allow(unused_imports)]
  use self::flatbuffers::flexbuffers;
  #[allow(unused_imports)]
  use std::cmp::Ordering;

pub enum InParentNamespaceOffset {}
pub struct InParentNamespace<'a> {
  pub _tab: flatbuffers::Table<'a>,
  _phantom: PhantomData<&'a ()>,
}
// impl<'a> flatbuffers::Table for InParentNamespace<'a> {
//impl<'a> flatbuffers::BufferBacked<'a> for InParentNamespace<'a> {
impl<'a> flatbuffers::BufferBacked<'a> for InParentNamespace<'a> {
    fn init_from_bytes(bytes: &'a [u8], pos: usize) -> Self {
        InParentNamespace {
            _tab: flatbuffers::Table {
                data: bytes,
                pos: pos,
            },
            _phantom: PhantomData,
        }
    }
}
impl<'a> InParentNamespace<'a> /* private flatbuffers::Table */ {
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        InParentNamespace {
            _tab: table,
            _phantom: PhantomData,
        }
    }
}

pub struct InParentNamespaceArgs<'a> {
    pub _phantom: PhantomData<&'a ()>, // pub for default trait
}
impl<'a> Default for InParentNamespaceArgs<'a> {
    fn default() -> Self {
        InParentNamespaceArgs {
            _phantom: PhantomData,
        }
    }
}
pub struct InParentNamespaceBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::LabeledUOffsetT<flatbuffers::TableOffset>,
}
impl<'a: 'b, 'b> InParentNamespaceBuilder<'a, 'b> {
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> InParentNamespaceBuilder<'a, 'b> {
    let start = _fbb.start_table(0);
    InParentNamespaceBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  // InParentNamespaceBuilder &operator=(const InParentNamespaceBuilder &);
  //pub fn finish<'c>(mut self) -> flatbuffers::LabeledUOffsetT<flatbuffers::TableOffset> {
  pub fn finish<'c>(mut self) -> flatbuffers::LabeledUOffsetT<InParentNamespaceOffset> {
    let o = self.fbb_.end_table(self.start_);
    //let o = flatbuffers::LabeledUOffsetT::<InParentNamespaceOffset>::new(end);
    flatbuffers::LabeledUOffsetT::new(o.value())
  }
}

#[inline]
pub fn CreateInParentNamespace<'a: 'b, 'b>(
    _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    args: &InParentNamespaceArgs) -> flatbuffers::LabeledUOffsetT<InParentNamespaceOffset> {
  let mut builder = InParentNamespaceBuilder::new(_fbb);
  builder.finish()
}

pub mod Example2 {
  #[allow(unused_imports)]
  use std::mem;
  #[allow(unused_imports)]
  use std::marker::PhantomData;
  #[allow(unused_imports)]
  #[allow(unreachable_code)]
  extern crate flatbuffers;
  #[allow(unused_imports)]
  use self::flatbuffers::flexbuffers;
  #[allow(unused_imports)]
  use std::cmp::Ordering;

pub enum MonsterOffset {}
pub struct Monster<'a> {
  pub _tab: flatbuffers::Table<'a>,
  _phantom: PhantomData<&'a ()>,
}
// impl<'a> flatbuffers::Table for Monster<'a> {
//impl<'a> flatbuffers::BufferBacked<'a> for Monster<'a> {
impl<'a> flatbuffers::BufferBacked<'a> for Monster<'a> {
    fn init_from_bytes(bytes: &'a [u8], pos: usize) -> Self {
        Monster {
            _tab: flatbuffers::Table {
                data: bytes,
                pos: pos,
            },
            _phantom: PhantomData,
        }
    }
}
impl<'a> Monster<'a> /* private flatbuffers::Table */ {
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        Monster {
            _tab: table,
            _phantom: PhantomData,
        }
    }
}

pub struct MonsterArgs<'a> {
    pub _phantom: PhantomData<&'a ()>, // pub for default trait
}
impl<'a> Default for MonsterArgs<'a> {
    fn default() -> Self {
        MonsterArgs {
            _phantom: PhantomData,
        }
    }
}
pub struct MonsterBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::LabeledUOffsetT<flatbuffers::TableOffset>,
}
impl<'a: 'b, 'b> MonsterBuilder<'a, 'b> {
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> MonsterBuilder<'a, 'b> {
    let start = _fbb.start_table(0);
    MonsterBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  // MonsterBuilder &operator=(const MonsterBuilder &);
  //pub fn finish<'c>(mut self) -> flatbuffers::LabeledUOffsetT<flatbuffers::TableOffset> {
  pub fn finish<'c>(mut self) -> flatbuffers::LabeledUOffsetT<MonsterOffset> {
    let o = self.fbb_.end_table(self.start_);
    //let o = flatbuffers::LabeledUOffsetT::<MonsterOffset>::new(end);
    flatbuffers::LabeledUOffsetT::new(o.value())
  }
}

#[inline]
pub fn CreateMonster<'a: 'b, 'b>(
    _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    args: &MonsterArgs) -> flatbuffers::LabeledUOffsetT<MonsterOffset> {
  let mut builder = MonsterBuilder::new(_fbb);
  builder.finish()
}

}  // pub mod Example2

pub mod Example {
  #[allow(unused_imports)]
  use std::mem;
  #[allow(unused_imports)]
  use std::marker::PhantomData;
  #[allow(unused_imports)]
  #[allow(unreachable_code)]
  extern crate flatbuffers;
  #[allow(unused_imports)]
  use self::flatbuffers::flexbuffers;
  #[allow(unused_imports)]
  use std::cmp::Ordering;

#[repr(i8)]
#[derive(Clone, Copy, PartialEq, Debug)]
pub enum Color {
  Red = 1,
  Green = 2,
  Blue = 8
}

const EnumValuesColor:[Color; 3] = [
  Color::Red,
  Color::Green,
  Color::Blue
];

const EnumNamesColor:[&'static str; 8] = [
    "Red",
    "Green",
    "",
    "",
    "",
    "",
    "",
    "Blue"
];

pub fn EnumNameColor(e: Color) -> &'static str {
  let index: usize = e as usize - Color::Red as usize;
  EnumNamesColor[index]
}

#[repr(u8)]
#[derive(Clone, Copy, PartialEq, Debug)]
pub enum Farts {
  Red = 0,
  Blue = 1,
  Green = 2
}

const EnumValuesFarts:[Farts; 3] = [
  Farts::Red,
  Farts::Blue,
  Farts::Green
];

const EnumNamesFarts:[&'static str; 3] = [
    "Red",
    "Blue",
    "Green"
];

pub fn EnumNameFarts(e: Farts) -> &'static str {
  let index: usize = e as usize;
  EnumNamesFarts[index]
}

#[repr(u8)]
#[derive(Clone, Copy, PartialEq, Debug)]
pub enum Any {
  NONE = 0,
  Monster = 1,
  TestSimpleTableWithEnum = 2,
  MyGame_Example2_Monster = 3
}

const EnumValuesAny:[Any; 4] = [
  Any::NONE,
  Any::Monster,
  Any::TestSimpleTableWithEnum,
  Any::MyGame_Example2_Monster
];

const EnumNamesAny:[&'static str; 4] = [
    "NONE",
    "Monster",
    "TestSimpleTableWithEnum",
    "MyGame_Example2_Monster"
];

pub fn EnumNameAny(e: Any) -> &'static str {
  let index: usize = e as usize;
  EnumNamesAny[index]
}

// MANUALLY_ALIGNED_STRUCT(2)
#[repr(C, packed)]
#[derive(Clone, Copy, Default, Debug)]
pub struct Test {
  a_: i16,
  b_: i8,
  padding0__: u8,
} // pub struct Test
impl flatbuffers::GeneratedStruct for Test {}

impl Test {
  pub fn Reset(&mut self) {
    //memset(this, 0, size_of(Test));
  }
  pub fn new(_a: i16, _b: i8) -> Self {
    Test {
      a_: flatbuffers::endian_scalar(_a),
      b_: flatbuffers::endian_scalar(_b),


        padding0__: 0,
    }
  }
  pub fn a(&self) -> i16 {
    flatbuffers::endian_scalar(self.a_)
  }
  pub fn b(&self) -> i8 {
    flatbuffers::endian_scalar(self.b_)
  }
}
// STRUCT_END(Test, 4);

// MANUALLY_ALIGNED_STRUCT(16)
#[repr(C, packed)]
#[derive(Clone, Copy, Default, Debug)]
pub struct Vec3 {
  x_: f32,
  y_: f32,
  z_: f32,
  padding0__: u32,
  test1_: f64,
  test2_: i8,
  padding1__: u8,
  test3_: Test/* foo */,
  padding2__: u16,
} // pub struct Vec3
impl flatbuffers::GeneratedStruct for Vec3 {}

impl Vec3 {
  pub fn Reset(&mut self) {
    //memset(this, 0, size_of(Vec3));
  }
  pub fn new(_x: f32, _y: f32, _z: f32, _test1: f64, _test2: i8, _test3: Test/* foo */) -> Self {
    Vec3 {
      x_: _x,
      y_: _y,
      z_: _z,
      test1_: _test1,
      test2_: flatbuffers::endian_scalar(_test2 as i8),
      test3_: _test3,


        padding0__: 0,

        padding1__: 0,

        padding2__: 0,
    }
  }
  pub fn x(&self) -> f32 {
    self.x_
  }
  pub fn y(&self) -> f32 {
    self.y_
  }
  pub fn z(&self) -> f32 {
    self.z_
  }
  pub fn test1(&self) -> f64 {
    self.test1_
  }
  pub fn test2(&self) -> Color {
    unsafe { ::std::mem::transmute(flatbuffers::endian_scalar(self.test2_)) }
  }
  pub fn test3(&self) -> & Test {
    &self.test3_
  }
}
// STRUCT_END(Vec3, 32);

// MANUALLY_ALIGNED_STRUCT(4)
#[repr(C, packed)]
#[derive(Clone, Copy, Default, Debug)]
pub struct Ability {
  id_: u32,
  distance_: u32,
} // pub struct Ability
impl flatbuffers::GeneratedStruct for Ability {}

impl Ability {
  pub fn Reset(&mut self) {
    //memset(this, 0, size_of(Ability));
  }
  pub fn new(_id: u32, _distance: u32) -> Self {
    Ability {
      id_: flatbuffers::endian_scalar(_id),
      distance_: flatbuffers::endian_scalar(_distance),

    }
  }
  pub fn id(&self) -> u32 {
    flatbuffers::endian_scalar(self.id_)
  }
  fn KeyCompareLessThan(&self, o: &Ability) -> bool {
    unimplemented!();
    //self.id() < o.id()
  }
  fn KeyCompareWithValue(&self, val: u32) -> isize {
    let key = self.id();
    (key > val) as isize - (key < val) as isize
  }
  pub fn distance(&self) -> u32 {
    flatbuffers::endian_scalar(self.distance_)
  }
}
// STRUCT_END(Ability, 8);

pub enum TestSimpleTableWithEnumOffset {}
pub struct TestSimpleTableWithEnum<'a> {
  pub _tab: flatbuffers::Table<'a>,
  _phantom: PhantomData<&'a ()>,
}
// impl<'a> flatbuffers::Table for TestSimpleTableWithEnum<'a> {
//impl<'a> flatbuffers::BufferBacked<'a> for TestSimpleTableWithEnum<'a> {
impl<'a> flatbuffers::BufferBacked<'a> for TestSimpleTableWithEnum<'a> {
    fn init_from_bytes(bytes: &'a [u8], pos: usize) -> Self {
        TestSimpleTableWithEnum {
            _tab: flatbuffers::Table {
                data: bytes,
                pos: pos,
            },
            _phantom: PhantomData,
        }
    }
}
impl<'a> TestSimpleTableWithEnum<'a> /* private flatbuffers::Table */ {
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        TestSimpleTableWithEnum {
            _tab: table,
            _phantom: PhantomData,
        }
    }
    pub const VT_COLOR: flatbuffers::VOffsetT = 4;

  pub fn color(&self) -> Color {
    self._tab.get_slot_scalar::<i8>(TestSimpleTableWithEnum::VT_COLOR) as Color
  }
}

pub struct TestSimpleTableWithEnumArgs<'a> {
    pub color: Color,
    pub _phantom: PhantomData<&'a ()>, // pub for default trait
}
impl<'a> Default for TestSimpleTableWithEnumArgs<'a> {
    fn default() -> Self {
        TestSimpleTableWithEnumArgs {
            color: Color::Green,
            _phantom: PhantomData,
        }
    }
}
pub struct TestSimpleTableWithEnumBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::LabeledUOffsetT<flatbuffers::TableOffset>,
}
impl<'a: 'b, 'b> TestSimpleTableWithEnumBuilder<'a, 'b> {
  pub fn add_color(&mut self, color: Color) {
    self.fbb_.push_slot_scalar::<i8>(TestSimpleTableWithEnum::VT_COLOR, color as i8, Color::Green as i8);
  }
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> TestSimpleTableWithEnumBuilder<'a, 'b> {
    let start = _fbb.start_table(1);
    TestSimpleTableWithEnumBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  // TestSimpleTableWithEnumBuilder &operator=(const TestSimpleTableWithEnumBuilder &);
  //pub fn finish<'c>(mut self) -> flatbuffers::LabeledUOffsetT<flatbuffers::TableOffset> {
  pub fn finish<'c>(mut self) -> flatbuffers::LabeledUOffsetT<TestSimpleTableWithEnumOffset> {
    let o = self.fbb_.end_table(self.start_);
    //let o = flatbuffers::LabeledUOffsetT::<TestSimpleTableWithEnumOffset>::new(end);
    flatbuffers::LabeledUOffsetT::new(o.value())
  }
}

#[inline]
pub fn CreateTestSimpleTableWithEnum<'a: 'b, 'b>(
    _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    args: &TestSimpleTableWithEnumArgs) -> flatbuffers::LabeledUOffsetT<TestSimpleTableWithEnumOffset> {
  let mut builder = TestSimpleTableWithEnumBuilder::new(_fbb);
  builder.add_color(args.color);
  builder.finish()
}

pub enum StatOffset {}
pub struct Stat<'a> {
  pub _tab: flatbuffers::Table<'a>,
  _phantom: PhantomData<&'a ()>,
}
// impl<'a> flatbuffers::Table for Stat<'a> {
//impl<'a> flatbuffers::BufferBacked<'a> for Stat<'a> {
impl<'a> flatbuffers::BufferBacked<'a> for Stat<'a> {
    fn init_from_bytes(bytes: &'a [u8], pos: usize) -> Self {
        Stat {
            _tab: flatbuffers::Table {
                data: bytes,
                pos: pos,
            },
            _phantom: PhantomData,
        }
    }
}
impl<'a> Stat<'a> /* private flatbuffers::Table */ {
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        Stat {
            _tab: table,
            _phantom: PhantomData,
        }
    }
    pub const VT_ID: flatbuffers::VOffsetT = 4;
    pub const VT_VAL: flatbuffers::VOffsetT = 6;
    pub const VT_COUNT: flatbuffers::VOffsetT = 8;

  pub fn id(&self) -> Some<flatbuffers::Offset<flatbuffers::String<'a>>> {
    self._tab.get_slot_string(Stat::VT_ID)
  }
  pub fn val(&self) -> i64 {
    self._tab.get_slot_scalar::<i64>(Stat::VT_VAL, 0)
  }
  pub fn count(&self) -> u16 {
    self._tab.get_slot_scalar::<u16>(Stat::VT_COUNT, 0)
  }
}

pub struct StatArgs<'a> {
    pub id: Option<flatbuffers::StringOffset>,
    pub val: i64,
    pub count: u16,
    pub _phantom: PhantomData<&'a ()>, // pub for default trait
}
impl<'a> Default for StatArgs<'a> {
    fn default() -> Self {
        StatArgs {
            id: None,
            val: 0,
            count: 0,
            _phantom: PhantomData,
        }
    }
}
pub struct StatBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::LabeledUOffsetT<flatbuffers::TableOffset>,
}
impl<'a: 'b, 'b> StatBuilder<'a, 'b> {
  pub fn add_id(&mut self, id: flatbuffers::StringOffset) {
    flatbuffers::StringOffset(Stat::VT_ID, id);
  }
  pub fn add_val(&mut self, val: i64) {
    self.fbb_.push_slot_scalar::<i64>(Stat::VT_VAL, val, 0);
  }
  pub fn add_count(&mut self, count: u16) {
    self.fbb_.push_slot_scalar::<u16>(Stat::VT_COUNT, count, 0);
  }
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> StatBuilder<'a, 'b> {
    let start = _fbb.start_table(3);
    StatBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  // StatBuilder &operator=(const StatBuilder &);
  //pub fn finish<'c>(mut self) -> flatbuffers::LabeledUOffsetT<flatbuffers::TableOffset> {
  pub fn finish<'c>(mut self) -> flatbuffers::LabeledUOffsetT<StatOffset> {
    let o = self.fbb_.end_table(self.start_);
    //let o = flatbuffers::LabeledUOffsetT::<StatOffset>::new(end);
    flatbuffers::LabeledUOffsetT::new(o.value())
  }
}

#[inline]
pub fn CreateStat<'a: 'b, 'b>(
    _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    args: &StatArgs) -> flatbuffers::LabeledUOffsetT<StatOffset> {
  let mut builder = StatBuilder::new(_fbb);
  builder.add_val(args.val);
  if let Some(x) = args.id { builder.add_id(x); }
  builder.add_count(args.count);
  builder.finish()
}

/// an example documentation comment: monster object
pub enum MonsterOffset {}
pub struct Monster<'a> {
  pub _tab: flatbuffers::Table<'a>,
  _phantom: PhantomData<&'a ()>,
}
// impl<'a> flatbuffers::Table for Monster<'a> {
//impl<'a> flatbuffers::BufferBacked<'a> for Monster<'a> {
impl<'a> flatbuffers::BufferBacked<'a> for Monster<'a> {
    fn init_from_bytes(bytes: &'a [u8], pos: usize) -> Self {
        Monster {
            _tab: flatbuffers::Table {
                data: bytes,
                pos: pos,
            },
            _phantom: PhantomData,
        }
    }
}
impl<'a> Monster<'a> /* private flatbuffers::Table */ {
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        Monster {
            _tab: table,
            _phantom: PhantomData,
        }
    }
    pub const VT_POS: flatbuffers::VOffsetT = 4;
    pub const VT_MANA: flatbuffers::VOffsetT = 6;
    pub const VT_HP: flatbuffers::VOffsetT = 8;
    pub const VT_NAME: flatbuffers::VOffsetT = 10;
    pub const VT_INVENTORY: flatbuffers::VOffsetT = 14;
    pub const VT_COLOR: flatbuffers::VOffsetT = 16;
    pub const VT_TEST_TYPE: flatbuffers::VOffsetT = 18;
    pub const VT_TEST: flatbuffers::VOffsetT = 20;
    pub const VT_TEST4: flatbuffers::VOffsetT = 22;
    pub const VT_TESTARRAYOFSTRING: flatbuffers::VOffsetT = 24;
    pub const VT_TESTARRAYOFTABLES: flatbuffers::VOffsetT = 26;
    pub const VT_ENEMY: flatbuffers::VOffsetT = 28;
    pub const VT_TESTNESTEDFLATBUFFER: flatbuffers::VOffsetT = 30;
    pub const VT_TESTEMPTY: flatbuffers::VOffsetT = 32;
    pub const VT_TESTBOOL: flatbuffers::VOffsetT = 34;
    pub const VT_TESTHASHS32_FNV1: flatbuffers::VOffsetT = 36;
    pub const VT_TESTHASHU32_FNV1: flatbuffers::VOffsetT = 38;
    pub const VT_TESTHASHS64_FNV1: flatbuffers::VOffsetT = 40;
    pub const VT_TESTHASHU64_FNV1: flatbuffers::VOffsetT = 42;
    pub const VT_TESTHASHS32_FNV1A: flatbuffers::VOffsetT = 44;
    pub const VT_TESTHASHU32_FNV1A: flatbuffers::VOffsetT = 46;
    pub const VT_TESTHASHS64_FNV1A: flatbuffers::VOffsetT = 48;
    pub const VT_TESTHASHU64_FNV1A: flatbuffers::VOffsetT = 50;
    pub const VT_TESTARRAYOFBOOLS: flatbuffers::VOffsetT = 52;
    pub const VT_TESTF: flatbuffers::VOffsetT = 54;
    pub const VT_TESTF2: flatbuffers::VOffsetT = 56;
    pub const VT_TESTF3: flatbuffers::VOffsetT = 58;
    pub const VT_TESTARRAYOFSTRING2: flatbuffers::VOffsetT = 60;
    pub const VT_TESTARRAYOFSORTEDSTRUCT: flatbuffers::VOffsetT = 62;
    pub const VT_FLEX: flatbuffers::VOffsetT = 64;
    pub const VT_TEST5: flatbuffers::VOffsetT = 66;
    pub const VT_VECTOR_OF_LONGS: flatbuffers::VOffsetT = 68;
    pub const VT_VECTOR_OF_DOUBLES: flatbuffers::VOffsetT = 70;
    pub const VT_PARENT_NAMESPACE_TEST: flatbuffers::VOffsetT = 72;
    pub const VT_FOO0: flatbuffers::VOffsetT = 74;
    pub const VT_FOO1: flatbuffers::VOffsetT = 76;
    pub const VT_FOO2: flatbuffers::VOffsetT = 78;
    pub const VT_FOO3: flatbuffers::VOffsetT = 80;
    pub const VT_FOO4: flatbuffers::VOffsetT = 82;
    pub const VT_FOO5: flatbuffers::VOffsetT = 84;

  pub fn pos(&self) -> Option<&'a Vec3> {
    self._tab.get_slot_struct::<Vec3>(Monster::VT_POS)
  }
  pub fn mana(&self) -> i16 {
    self._tab.get_slot_scalar::<i16>(Monster::VT_MANA, 0)
  }
  pub fn hp(&self) -> i16 {
    self._tab.get_slot_scalar::<i16>(Monster::VT_HP, 0)
  }
  pub fn name(&self) -> Some<flatbuffers::Offset<flatbuffers::String<'a>>> {
    self._tab.get_slot_string(Monster::VT_NAME)
  }
  fn KeyCompareLessThan(&self, o: &Monster) -> bool {
    unimplemented!()
    //return *self.name() < *o.name();
  }
  fn KeyCompareWithValue(&self, _val: &str) -> Ordering {
    unimplemented!();
    Ordering::Equal
    // TODO(rw): self.name().cmp(val)
  }
  pub fn inventory(&self) -> Option<flatbuffers::Vector<&'a VectorOffset>> {
    self._tab.get_slot_vector::<&'a u8>(Monster::VT_INVENTORY)
  }
  pub fn color(&self) -> Color {
    self._tab.get_slot_scalar::<i8>(Monster::VT_COLOR) as Color
  }
  pub fn test_type(&self) -> Any {
    self._tab.get_slot_scalar::<u8>(Monster::VT_TEST_TYPE) as Any
  }
  pub fn test(&self) -> Option<&'a Any_UnionTable<'a>> {
    self._tab.get_slot_struct::<Any_UnionTable>(Monster::VT_TEST)
  }
  pub fn test4(&self) -> Option<flatbuffers::Vector<&'a Test>> {
    self._tab.get_slot_vector::<&'a Test>(Monster::VT_TEST4)
  }
  pub fn testarrayofstring(&self) -> Option<flatbuffers::Vector<&'a flatbuffers::String<'a>>> {
    self._tab.get_slot_vector::<&'a flatbuffers::String<'a>>(Monster::VT_TESTARRAYOFSTRING)
  }
  /// an example documentation comment: this will end up in the generated code
  /// multiline too
  pub fn testarrayoftables(&self) -> Option<flatbuffers::Vector<&'a Monster<'a>>> {
    self._tab.get_slot_vector::<&'a Monster<'a>>(Monster::VT_TESTARRAYOFTABLES)
  }
  pub fn enemy(&self) -> Option<&'a Monster<'a>> {
    self._tab.get_slot_struct::<Monster>(Monster::VT_ENEMY)
  }
  pub fn testnestedflatbuffer(&self) -> Option<flatbuffers::Vector<&'a VectorOffset>> {
    self._tab.get_slot_vector::<&'a u8>(Monster::VT_TESTNESTEDFLATBUFFER)
  }
  pub fn testempty(&self) -> Option<&'a Stat<'a>> {
    self._tab.get_slot_struct::<Stat>(Monster::VT_TESTEMPTY)
  }
  pub fn testbool(&self) -> bool {
    self._tab.get_slot_scalar::<u8>(Monster::VT_TESTBOOL, 0)
  }
  pub fn testhashs32_fnv1(&self) -> i32 {
    self._tab.get_slot_scalar::<i32>(Monster::VT_TESTHASHS32_FNV1, 0)
  }
  pub fn testhashu32_fnv1(&self) -> u32 {
    self._tab.get_slot_scalar::<u32>(Monster::VT_TESTHASHU32_FNV1, 0)
  }
  pub fn testhashs64_fnv1(&self) -> i64 {
    self._tab.get_slot_scalar::<i64>(Monster::VT_TESTHASHS64_FNV1, 0)
  }
  pub fn testhashu64_fnv1(&self) -> u64 {
    self._tab.get_slot_scalar::<u64>(Monster::VT_TESTHASHU64_FNV1, 0)
  }
  pub fn testhashs32_fnv1a(&self) -> i32 {
    self._tab.get_slot_scalar::<i32>(Monster::VT_TESTHASHS32_FNV1A, 0)
  }
  pub fn testhashu32_fnv1a(&self) -> u32 {
    self._tab.get_slot_scalar::<u32>(Monster::VT_TESTHASHU32_FNV1A, 0)
  }
  pub fn testhashs64_fnv1a(&self) -> i64 {
    self._tab.get_slot_scalar::<i64>(Monster::VT_TESTHASHS64_FNV1A, 0)
  }
  pub fn testhashu64_fnv1a(&self) -> u64 {
    self._tab.get_slot_scalar::<u64>(Monster::VT_TESTHASHU64_FNV1A, 0)
  }
  pub fn testarrayofbools(&self) -> Option<flatbuffers::Vector<&'a bool>> {
    self._tab.get_slot_vector::<&'a bool>(Monster::VT_TESTARRAYOFBOOLS)
  }
  pub fn testf(&self) -> f32 {
    self._tab.get_slot_scalar::<f32>(Monster::VT_TESTF, 0)
  }
  pub fn testf2(&self) -> f32 {
    self._tab.get_slot_scalar::<f32>(Monster::VT_TESTF2, 0)
  }
  pub fn testf3(&self) -> f32 {
    self._tab.get_slot_scalar::<f32>(Monster::VT_TESTF3, 0)
  }
  pub fn testarrayofstring2(&self) -> Option<flatbuffers::Vector<&'a flatbuffers::String<'a>>> {
    self._tab.get_slot_vector::<&'a flatbuffers::String<'a>>(Monster::VT_TESTARRAYOFSTRING2)
  }
  pub fn testarrayofsortedstruct(&self) -> Option<flatbuffers::Vector<&'a Ability>> {
    self._tab.get_slot_vector::<&'a Ability>(Monster::VT_TESTARRAYOFSORTEDSTRUCT)
  }
  pub fn flex(&self) -> Option<flatbuffers::Vector<&'a VectorOffset>> {
    self._tab.get_slot_vector::<&'a u8>(Monster::VT_FLEX)
  }
  pub fn test5(&self) -> Option<flatbuffers::Vector<&'a Test>> {
    self._tab.get_slot_vector::<&'a Test>(Monster::VT_TEST5)
  }
  pub fn vector_of_longs(&self) -> Option<flatbuffers::Vector<&'a VectorOffset>> {
    self._tab.get_slot_vector::<&'a i64>(Monster::VT_VECTOR_OF_LONGS)
  }
  pub fn vector_of_doubles(&self) -> Option<flatbuffers::Vector<&'a VectorOffset>> {
    self._tab.get_slot_vector::<&'a f64>(Monster::VT_VECTOR_OF_DOUBLES)
  }
  pub fn parent_namespace_test(&self) -> Option<&'a MyGame::InParentNamespace<'a>> {
    self._tab.get_slot_struct::<MyGame::InParentNamespace>(Monster::VT_PARENT_NAMESPACE_TEST)
  }
  pub fn foo0(&self) -> Option<flatbuffers::Vector<&'a Color>> {
    self._tab.get_slot_vector::<&'a Color>(Monster::VT_FOO0)
  }
  pub fn foo1(&self) -> Option<&'a Test> {
    self._tab.get_slot_struct::<Test>(Monster::VT_FOO1)
  }
  pub fn foo2(&self) -> Option<flatbuffers::Vector<&'a MyGame::InParentNamespace<'a>>> {
    self._tab.get_slot_vector::<&'a MyGame::InParentNamespace<'a>>(Monster::VT_FOO2)
  }
  pub fn foo3(&self) -> Option<flatbuffers::Vector<&'a Vec3>> {
    self._tab.get_slot_vector::<&'a Vec3>(Monster::VT_FOO3)
  }
  pub fn foo4(&self) -> Color {
    self._tab.get_slot_scalar::<i8>(Monster::VT_FOO4) as Color
  }
  pub fn foo5(&self) -> Option<&'a Monster<'a>> {
    self._tab.get_slot_struct::<Monster>(Monster::VT_FOO5)
  }
}

//TODO: inject these functions into impl for type
//#[inline]
//fn Monster_MEMBER_test_as_X_Monster_X() -> &Monster {
//  return test_as_Monster();
//}
//
//TODO: inject these functions into impl for type
//#[inline]
//fn Monster_MEMBER_test_as_X_TestSimpleTableWithEnum_X() -> &TestSimpleTableWithEnum {
//  return test_as_TestSimpleTableWithEnum();
//}
//
//TODO: inject these functions into impl for type
//#[inline]
//fn Monster_MEMBER_test_as_X_super::Example2::Monster_X() -> &super::Example2::Monster {
//  return test_as_MyGame_Example2_Monster();
//}
//
pub struct MonsterArgs<'a> {
    pub pos: Option<&'a  Vec3>,
    pub mana: i16,
    pub hp: i16,
    pub name: Option<flatbuffers::StringOffset>,
    pub inventory: Option<flatbuffers::Vector<&'a  VectorOffset>>,
    pub color: Color,
    pub test_type: Any,
    pub test: Option<AnyUnionOffset>,
    pub test4: Option<flatbuffers::Vector<&'a  Test>>,
    pub testarrayofstring: Option<flatbuffers::Vector<&'a  flatbuffers::String<'a >>>,
    pub testarrayoftables: Option<flatbuffers::Vector<&'a  Monster<'a >>>,
    pub enemy: Option<&'a  Monster<'a >>,
    pub testnestedflatbuffer: Option<flatbuffers::Vector<&'a  VectorOffset>>,
    pub testempty: Option<&'a  Stat<'a >>,
    pub testbool: u8,
    pub testhashs32_fnv1: i32,
    pub testhashu32_fnv1: u32,
    pub testhashs64_fnv1: i64,
    pub testhashu64_fnv1: u64,
    pub testhashs32_fnv1a: i32,
    pub testhashu32_fnv1a: u32,
    pub testhashs64_fnv1a: i64,
    pub testhashu64_fnv1a: u64,
    pub testarrayofbools: Option<flatbuffers::Vector<&'a  bool>>,
    pub testf: f32,
    pub testf2: f32,
    pub testf3: f32,
    pub testarrayofstring2: Option<flatbuffers::Vector<&'a  flatbuffers::String<'a >>>,
    pub testarrayofsortedstruct: Option<flatbuffers::Vector<&'a  Ability>>,
    pub flex: Option<flatbuffers::Vector<&'a  VectorOffset>>,
    pub test5: Option<flatbuffers::Vector<&'a  Test>>,
    pub vector_of_longs: Option<flatbuffers::Vector<&'a  VectorOffset>>,
    pub vector_of_doubles: Option<flatbuffers::Vector<&'a  VectorOffset>>,
    pub parent_namespace_test: Option<&'a  MyGame::InParentNamespace<'a >>,
    pub foo0: Option<flatbuffers::Vector<&'a  Color>>,
    pub foo1: Option<&'a  Test>,
    pub foo2: Option<flatbuffers::Vector<&'a  MyGame::InParentNamespace<'a >>>,
    pub foo3: Option<flatbuffers::Vector<&'a  Vec3>>,
    pub foo4: Color,
    pub foo5: Option<&'a  Monster<'a >>,
    pub _phantom: PhantomData<&'a ()>, // pub for default trait
}
impl<'a> Default for MonsterArgs<'a> {
    fn default() -> Self {
        MonsterArgs {
            pos: None,
            mana: 150,
            hp: 100,
 // required
            name: None,
            inventory: None,
            color: Color::Blue,
            test_type: Any::NONE,
            test: None,
            test4: None,
            testarrayofstring: None,
            testarrayoftables: None,
            enemy: None,
            testnestedflatbuffer: None,
            testempty: None,
            testbool: false,
            testhashs32_fnv1: 0,
            testhashu32_fnv1: 0,
            testhashs64_fnv1: 0,
            testhashu64_fnv1: 0,
            testhashs32_fnv1a: 0,
            testhashu32_fnv1a: 0,
            testhashs64_fnv1a: 0,
            testhashu64_fnv1a: 0,
            testarrayofbools: None,
            testf: 3.14159,
            testf2: 3.0,
            testf3: 0.0,
            testarrayofstring2: None,
            testarrayofsortedstruct: None,
            flex: None,
            test5: None,
            vector_of_longs: None,
            vector_of_doubles: None,
            parent_namespace_test: None,
            foo0: None,
            foo1: None,
            foo2: None,
            foo3: None,
            foo4: Color::Green,
            foo5: None,
            _phantom: PhantomData,
        }
    }
}
pub struct MonsterBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::LabeledUOffsetT<flatbuffers::TableOffset>,
}
impl<'a: 'b, 'b> MonsterBuilder<'a, 'b> {
  pub fn add_pos(&mut self, pos: &'a  Vec3) {
    self.fbb_.push_slot_struct::<Vec3/* foo */>(Monster::VT_POS, pos);
  }
  pub fn add_mana(&mut self, mana: i16) {
    self.fbb_.push_slot_scalar::<i16>(Monster::VT_MANA, mana, 150);
  }
  pub fn add_hp(&mut self, hp: i16) {
    self.fbb_.push_slot_scalar::<i16>(Monster::VT_HP, hp, 100);
  }
  pub fn add_name(&mut self, name: flatbuffers::StringOffset) {
    flatbuffers::StringOffset(Monster::VT_NAME, name);
  }
  pub fn add_inventory(&mut self, inventory: flatbuffers::Offset<flatbuffers::Vector<&'a  VectorOffset>>) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_INVENTORY, inventory);
  }
  pub fn add_color(&mut self, color: Color) {
    self.fbb_.push_slot_scalar::<i8>(Monster::VT_COLOR, color as i8, Color::Blue as i8);
  }
  pub fn add_test_type(&mut self, test_type: Any) {
    self.fbb_.push_slot_scalar::<u8>(Monster::VT_TEST_TYPE, test_type as u8, Any::NONE as u8);
  }
  pub fn add_test(&mut self, test: AnyUnionOffset) {
    self.fbb_.push_slot_labeled_uoffset_relative::<flatbuffersLabeledUOffsetT<Any>>(Monster::VT_TEST, test);
  }
  pub fn add_test4(&mut self, test4: flatbuffers::Offset<flatbuffers::Vector<&'a  Test>>) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_TEST4, test4);
  }
  pub fn add_testarrayofstring(&mut self, testarrayofstring: flatbuffers::Offset<flatbuffers::Vector<&'a  flatbuffers::String<'a >>>) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_TESTARRAYOFSTRING, testarrayofstring);
  }
  pub fn add_testarrayoftables(&mut self, testarrayoftables: flatbuffers::Offset<flatbuffers::Vector<&'a  Monster<'a >>>) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_TESTARRAYOFTABLES, testarrayoftables);
  }
  pub fn add_enemy(&mut self, enemy: &'a  Monster<'a>) {
    Monster<'a>(Monster::VT_ENEMY, enemy);
  }
  pub fn add_testnestedflatbuffer(&mut self, testnestedflatbuffer: flatbuffers::Offset<flatbuffers::Vector<&'a  VectorOffset>>) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_TESTNESTEDFLATBUFFER, testnestedflatbuffer);
  }
  pub fn add_testempty(&mut self, testempty: &'a  Stat<'a>) {
    Stat<'a>(Monster::VT_TESTEMPTY, testempty);
  }
  pub fn add_testbool(&mut self, testbool: bool) {
    bool(Monster::VT_TESTBOOL, testbool, false);
  }
  pub fn add_testhashs32_fnv1(&mut self, testhashs32_fnv1: i32) {
    self.fbb_.push_slot_scalar::<i32>(Monster::VT_TESTHASHS32_FNV1, testhashs32_fnv1, 0);
  }
  pub fn add_testhashu32_fnv1(&mut self, testhashu32_fnv1: u32) {
    self.fbb_.push_slot_scalar::<u32>(Monster::VT_TESTHASHU32_FNV1, testhashu32_fnv1, 0);
  }
  pub fn add_testhashs64_fnv1(&mut self, testhashs64_fnv1: i64) {
    self.fbb_.push_slot_scalar::<i64>(Monster::VT_TESTHASHS64_FNV1, testhashs64_fnv1, 0);
  }
  pub fn add_testhashu64_fnv1(&mut self, testhashu64_fnv1: u64) {
    self.fbb_.push_slot_scalar::<u64>(Monster::VT_TESTHASHU64_FNV1, testhashu64_fnv1, 0);
  }
  pub fn add_testhashs32_fnv1a(&mut self, testhashs32_fnv1a: i32) {
    self.fbb_.push_slot_scalar::<i32>(Monster::VT_TESTHASHS32_FNV1A, testhashs32_fnv1a, 0);
  }
  pub fn add_testhashu32_fnv1a(&mut self, testhashu32_fnv1a: u32) {
    self.fbb_.push_slot_scalar::<u32>(Monster::VT_TESTHASHU32_FNV1A, testhashu32_fnv1a, 0);
  }
  pub fn add_testhashs64_fnv1a(&mut self, testhashs64_fnv1a: i64) {
    self.fbb_.push_slot_scalar::<i64>(Monster::VT_TESTHASHS64_FNV1A, testhashs64_fnv1a, 0);
  }
  pub fn add_testhashu64_fnv1a(&mut self, testhashu64_fnv1a: u64) {
    self.fbb_.push_slot_scalar::<u64>(Monster::VT_TESTHASHU64_FNV1A, testhashu64_fnv1a, 0);
  }
  pub fn add_testarrayofbools(&mut self, testarrayofbools: flatbuffers::Offset<flatbuffers::Vector<&'a  bool>>) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_TESTARRAYOFBOOLS, testarrayofbools);
  }
  pub fn add_testf(&mut self, testf: f32) {
    self.fbb_.push_slot_scalar::<f32>(Monster::VT_TESTF, testf, 3.14159);
  }
  pub fn add_testf2(&mut self, testf2: f32) {
    self.fbb_.push_slot_scalar::<f32>(Monster::VT_TESTF2, testf2, 3.0);
  }
  pub fn add_testf3(&mut self, testf3: f32) {
    self.fbb_.push_slot_scalar::<f32>(Monster::VT_TESTF3, testf3, 0.0);
  }
  pub fn add_testarrayofstring2(&mut self, testarrayofstring2: flatbuffers::Offset<flatbuffers::Vector<&'a  flatbuffers::String<'a >>>) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_TESTARRAYOFSTRING2, testarrayofstring2);
  }
  pub fn add_testarrayofsortedstruct(&mut self, testarrayofsortedstruct: flatbuffers::Offset<flatbuffers::Vector<&'a  Ability>>) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_TESTARRAYOFSORTEDSTRUCT, testarrayofsortedstruct);
  }
  pub fn add_flex(&mut self, flex: flatbuffers::Offset<flatbuffers::Vector<&'a  VectorOffset>>) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_FLEX, flex);
  }
  pub fn add_test5(&mut self, test5: flatbuffers::Offset<flatbuffers::Vector<&'a  Test>>) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_TEST5, test5);
  }
  pub fn add_vector_of_longs(&mut self, vector_of_longs: flatbuffers::Offset<flatbuffers::Vector<&'a  VectorOffset>>) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_VECTOR_OF_LONGS, vector_of_longs);
  }
  pub fn add_vector_of_doubles(&mut self, vector_of_doubles: flatbuffers::Offset<flatbuffers::Vector<&'a  VectorOffset>>) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_VECTOR_OF_DOUBLES, vector_of_doubles);
  }
  pub fn add_parent_namespace_test(&mut self, parent_namespace_test: &'a  MyGame::InParentNamespace<'a>) {
    MyGame::InParentNamespace<'a>(Monster::VT_PARENT_NAMESPACE_TEST, parent_namespace_test);
  }
  pub fn add_foo0(&mut self, foo0: flatbuffers::Offset<flatbuffers::Vector<&'a  Color>>) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_FOO0, foo0);
  }
  pub fn add_foo1(&mut self, foo1: &'a  Test) {
    self.fbb_.push_slot_struct::<Test/* foo */>(Monster::VT_FOO1, foo1);
  }
  pub fn add_foo2(&mut self, foo2: flatbuffers::Offset<flatbuffers::Vector<&'a  MyGame::InParentNamespace<'a >>>) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_FOO2, foo2);
  }
  pub fn add_foo3(&mut self, foo3: flatbuffers::Offset<flatbuffers::Vector<&'a  Vec3>>) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_FOO3, foo3);
  }
  pub fn add_foo4(&mut self, foo4: Color) {
    self.fbb_.push_slot_scalar::<i8>(Monster::VT_FOO4, foo4 as i8, Color::Green as i8);
  }
  pub fn add_foo5(&mut self, foo5: &'a  Monster<'a>) {
    Monster<'a>(Monster::VT_FOO5, foo5);
  }
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> MonsterBuilder<'a, 'b> {
    let start = _fbb.start_table(41);
    MonsterBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  // MonsterBuilder &operator=(const MonsterBuilder &);
  //pub fn finish<'c>(mut self) -> flatbuffers::LabeledUOffsetT<flatbuffers::TableOffset> {
  pub fn finish<'c>(mut self) -> flatbuffers::LabeledUOffsetT<MonsterOffset> {
    let o = self.fbb_.end_table(self.start_);
    //let o = flatbuffers::LabeledUOffsetT::<MonsterOffset>::new(end);
    self.fbb_.required(&o, Monster::VT_NAME);
    flatbuffers::LabeledUOffsetT::new(o.value())
  }
}

#[inline]
pub fn CreateMonster<'a: 'b, 'b>(
    _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    args: &MonsterArgs) -> flatbuffers::LabeledUOffsetT<MonsterOffset> {
  let mut builder = MonsterBuilder::new(_fbb);
  builder.add_testhashu64_fnv1a(args.testhashu64_fnv1a);
  builder.add_testhashs64_fnv1a(args.testhashs64_fnv1a);
  builder.add_testhashu64_fnv1(args.testhashu64_fnv1);
  builder.add_testhashs64_fnv1(args.testhashs64_fnv1);
  if let Some(x) = args.foo5 { builder.add_foo5(x); }
  if let Some(x) = args.foo3 { builder.add_foo3(x); }
  if let Some(x) = args.foo2 { builder.add_foo2(x); }
  if let Some(x) = args.foo1 { builder.add_foo1(x); }
  if let Some(x) = args.foo0 { builder.add_foo0(x); }
  if let Some(x) = args.parent_namespace_test { builder.add_parent_namespace_test(x); }
  if let Some(x) = args.vector_of_doubles { builder.add_vector_of_doubles(x); }
  if let Some(x) = args.vector_of_longs { builder.add_vector_of_longs(x); }
  if let Some(x) = args.test5 { builder.add_test5(x); }
  if let Some(x) = args.flex { builder.add_flex(x); }
  if let Some(x) = args.testarrayofsortedstruct { builder.add_testarrayofsortedstruct(x); }
  if let Some(x) = args.testarrayofstring2 { builder.add_testarrayofstring2(x); }
  builder.add_testf3(args.testf3);
  builder.add_testf2(args.testf2);
  builder.add_testf(args.testf);
  if let Some(x) = args.testarrayofbools { builder.add_testarrayofbools(x); }
  builder.add_testhashu32_fnv1a(args.testhashu32_fnv1a);
  builder.add_testhashs32_fnv1a(args.testhashs32_fnv1a);
  builder.add_testhashu32_fnv1(args.testhashu32_fnv1);
  builder.add_testhashs32_fnv1(args.testhashs32_fnv1);
  if let Some(x) = args.testempty { builder.add_testempty(x); }
  if let Some(x) = args.testnestedflatbuffer { builder.add_testnestedflatbuffer(x); }
  if let Some(x) = args.enemy { builder.add_enemy(x); }
  if let Some(x) = args.testarrayoftables { builder.add_testarrayoftables(x); }
  if let Some(x) = args.testarrayofstring { builder.add_testarrayofstring(x); }
  if let Some(x) = args.test4 { builder.add_test4(x); }
  if let Some(x) = args.test { builder.add_test(x); }
  if let Some(x) = args.inventory { builder.add_inventory(x); }
  if let Some(x) = args.name { builder.add_name(x); }
  if let Some(x) = args.pos { builder.add_pos(x); }
  builder.add_hp(args.hp);
  builder.add_mana(args.mana);
  builder.add_foo4(args.foo4);
  builder.add_testbool(args.testbool);
  builder.add_test_type(args.test_type);
  builder.add_color(args.color);
  builder.finish()
}

pub enum TypeAliasesOffset {}
pub struct TypeAliases<'a> {
  pub _tab: flatbuffers::Table<'a>,
  _phantom: PhantomData<&'a ()>,
}
// impl<'a> flatbuffers::Table for TypeAliases<'a> {
//impl<'a> flatbuffers::BufferBacked<'a> for TypeAliases<'a> {
impl<'a> flatbuffers::BufferBacked<'a> for TypeAliases<'a> {
    fn init_from_bytes(bytes: &'a [u8], pos: usize) -> Self {
        TypeAliases {
            _tab: flatbuffers::Table {
                data: bytes,
                pos: pos,
            },
            _phantom: PhantomData,
        }
    }
}
impl<'a> TypeAliases<'a> /* private flatbuffers::Table */ {
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        TypeAliases {
            _tab: table,
            _phantom: PhantomData,
        }
    }
    pub const VT_I8_: flatbuffers::VOffsetT = 4;
    pub const VT_U8_: flatbuffers::VOffsetT = 6;
    pub const VT_I16_: flatbuffers::VOffsetT = 8;
    pub const VT_U16_: flatbuffers::VOffsetT = 10;
    pub const VT_I32_: flatbuffers::VOffsetT = 12;
    pub const VT_U32_: flatbuffers::VOffsetT = 14;
    pub const VT_I64_: flatbuffers::VOffsetT = 16;
    pub const VT_U64_: flatbuffers::VOffsetT = 18;
    pub const VT_F32_: flatbuffers::VOffsetT = 20;
    pub const VT_F64_: flatbuffers::VOffsetT = 22;
    pub const VT_V8: flatbuffers::VOffsetT = 24;
    pub const VT_VF64: flatbuffers::VOffsetT = 26;

  pub fn i8_(&self) -> i8 {
    self._tab.get_slot_scalar::<i8>(TypeAliases::VT_I8_, 0)
  }
  pub fn u8_(&self) -> u8 {
    self._tab.get_slot_scalar::<u8>(TypeAliases::VT_U8_, 0)
  }
  pub fn i16_(&self) -> i16 {
    self._tab.get_slot_scalar::<i16>(TypeAliases::VT_I16_, 0)
  }
  pub fn u16_(&self) -> u16 {
    self._tab.get_slot_scalar::<u16>(TypeAliases::VT_U16_, 0)
  }
  pub fn i32_(&self) -> i32 {
    self._tab.get_slot_scalar::<i32>(TypeAliases::VT_I32_, 0)
  }
  pub fn u32_(&self) -> u32 {
    self._tab.get_slot_scalar::<u32>(TypeAliases::VT_U32_, 0)
  }
  pub fn i64_(&self) -> i64 {
    self._tab.get_slot_scalar::<i64>(TypeAliases::VT_I64_, 0)
  }
  pub fn u64_(&self) -> u64 {
    self._tab.get_slot_scalar::<u64>(TypeAliases::VT_U64_, 0)
  }
  pub fn f32_(&self) -> f32 {
    self._tab.get_slot_scalar::<f32>(TypeAliases::VT_F32_, 0)
  }
  pub fn f64_(&self) -> f64 {
    self._tab.get_slot_scalar::<f64>(TypeAliases::VT_F64_, 0)
  }
  pub fn v8(&self) -> Option<flatbuffers::Vector<&'a VectorOffset>> {
    self._tab.get_slot_vector::<&'a i8>(TypeAliases::VT_V8)
  }
  pub fn vf64(&self) -> Option<flatbuffers::Vector<&'a VectorOffset>> {
    self._tab.get_slot_vector::<&'a f64>(TypeAliases::VT_VF64)
  }
}

pub struct TypeAliasesArgs<'a> {
    pub i8_: i8,
    pub u8_: u8,
    pub i16_: i16,
    pub u16_: u16,
    pub i32_: i32,
    pub u32_: u32,
    pub i64_: i64,
    pub u64_: u64,
    pub f32_: f32,
    pub f64_: f64,
    pub v8: Option<flatbuffers::Vector<&'a  VectorOffset>>,
    pub vf64: Option<flatbuffers::Vector<&'a  VectorOffset>>,
    pub _phantom: PhantomData<&'a ()>, // pub for default trait
}
impl<'a> Default for TypeAliasesArgs<'a> {
    fn default() -> Self {
        TypeAliasesArgs {
            i8_: 0,
            u8_: 0,
            i16_: 0,
            u16_: 0,
            i32_: 0,
            u32_: 0,
            i64_: 0,
            u64_: 0,
            f32_: 0.0,
            f64_: 0.0,
            v8: None,
            vf64: None,
            _phantom: PhantomData,
        }
    }
}
pub struct TypeAliasesBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::LabeledUOffsetT<flatbuffers::TableOffset>,
}
impl<'a: 'b, 'b> TypeAliasesBuilder<'a, 'b> {
  pub fn add_i8_(&mut self, i8_: i8) {
    self.fbb_.push_slot_scalar::<i8>(TypeAliases::VT_I8_, i8_, 0);
  }
  pub fn add_u8_(&mut self, u8_: u8) {
    self.fbb_.push_slot_scalar::<u8>(TypeAliases::VT_U8_, u8_, 0);
  }
  pub fn add_i16_(&mut self, i16_: i16) {
    self.fbb_.push_slot_scalar::<i16>(TypeAliases::VT_I16_, i16_, 0);
  }
  pub fn add_u16_(&mut self, u16_: u16) {
    self.fbb_.push_slot_scalar::<u16>(TypeAliases::VT_U16_, u16_, 0);
  }
  pub fn add_i32_(&mut self, i32_: i32) {
    self.fbb_.push_slot_scalar::<i32>(TypeAliases::VT_I32_, i32_, 0);
  }
  pub fn add_u32_(&mut self, u32_: u32) {
    self.fbb_.push_slot_scalar::<u32>(TypeAliases::VT_U32_, u32_, 0);
  }
  pub fn add_i64_(&mut self, i64_: i64) {
    self.fbb_.push_slot_scalar::<i64>(TypeAliases::VT_I64_, i64_, 0);
  }
  pub fn add_u64_(&mut self, u64_: u64) {
    self.fbb_.push_slot_scalar::<u64>(TypeAliases::VT_U64_, u64_, 0);
  }
  pub fn add_f32_(&mut self, f32_: f32) {
    self.fbb_.push_slot_scalar::<f32>(TypeAliases::VT_F32_, f32_, 0.0);
  }
  pub fn add_f64_(&mut self, f64_: f64) {
    self.fbb_.push_slot_scalar::<f64>(TypeAliases::VT_F64_, f64_, 0.0);
  }
  pub fn add_v8(&mut self, v8: flatbuffers::Offset<flatbuffers::Vector<&'a  VectorOffset>>) {
    self.fbb_.push_slot_labeled_uoffset_relative(TypeAliases::VT_V8, v8);
  }
  pub fn add_vf64(&mut self, vf64: flatbuffers::Offset<flatbuffers::Vector<&'a  VectorOffset>>) {
    self.fbb_.push_slot_labeled_uoffset_relative(TypeAliases::VT_VF64, vf64);
  }
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> TypeAliasesBuilder<'a, 'b> {
    let start = _fbb.start_table(12);
    TypeAliasesBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  // TypeAliasesBuilder &operator=(const TypeAliasesBuilder &);
  //pub fn finish<'c>(mut self) -> flatbuffers::LabeledUOffsetT<flatbuffers::TableOffset> {
  pub fn finish<'c>(mut self) -> flatbuffers::LabeledUOffsetT<TypeAliasesOffset> {
    let o = self.fbb_.end_table(self.start_);
    //let o = flatbuffers::LabeledUOffsetT::<TypeAliasesOffset>::new(end);
    flatbuffers::LabeledUOffsetT::new(o.value())
  }
}

#[inline]
pub fn CreateTypeAliases<'a: 'b, 'b>(
    _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    args: &TypeAliasesArgs) -> flatbuffers::LabeledUOffsetT<TypeAliasesOffset> {
  let mut builder = TypeAliasesBuilder::new(_fbb);
  builder.add_f64_(args.f64_);
  builder.add_u64_(args.u64_);
  builder.add_i64_(args.i64_);
  if let Some(x) = args.vf64 { builder.add_vf64(x); }
  if let Some(x) = args.v8 { builder.add_v8(x); }
  builder.add_f32_(args.f32_);
  builder.add_u32_(args.u32_);
  builder.add_i32_(args.i32_);
  builder.add_u16_(args.u16_);
  builder.add_i16_(args.i16_);
  builder.add_u8_(args.u8_);
  builder.add_i8_(args.i8_);
  builder.finish()
}

#[inline]
pub fn VerifyAny(verifier: &mut flatbuffers::Verifier, obj: &[u8], type_: Any) -> bool {
  match type_ {
    Any::NONE => {
      return true;
    }
    Any::Monster => {

      if obj.len() != mem::size_of::<Monster>() {
          return false;
      }
      let x: &Monster = unsafe {
        &*(obj.as_ptr() as *const Monster)
      };
      return verifier.verify_table::<&Monster>(x);
    }
    Any::TestSimpleTableWithEnum => {

      if obj.len() != mem::size_of::<TestSimpleTableWithEnum>() {
          return false;
      }
      let x: &TestSimpleTableWithEnum = unsafe {
        &*(obj.as_ptr() as *const TestSimpleTableWithEnum)
      };
      return verifier.verify_table::<&TestSimpleTableWithEnum>(x);
    }
    Any::MyGame_Example2_Monster => {

      if obj.len() != mem::size_of::<super::Example2::Monster>() {
          return false;
      }
      let x: &super::Example2::Monster = unsafe {
        &*(obj.as_ptr() as *const super::Example2::Monster)
      };
      return verifier.verify_table::<&super::Example2::Monster>(x);
    }
  }
}

#[inline]
pub fn VerifyAnyVector(_verifier: &mut flatbuffers::Verifier, values: &[flatbuffers::LabeledUOffsetT<flatbuffers::Void>], types: &[u8]) -> bool {
  //if values.len() == 0 || types.len() == 0 {
  //  return values.len() == types.len();
  //}
  if values.len() != types.len() { return false; }
  //for _i in (0 as flatbuffers::UOffsetT)..values.len() {
    //if !VerifyAny(
    //    verifier,  values.Get(i), types.GetEnum::<Any>(i)) {
    //  return false;
    //}
  //}
  return true;
}

#[inline]
pub fn GetRootAsMonster(buf: &[u8]) -> Monster  {
  //return flatbuffers::get_root::<&Monster>(buf);
  return flatbuffers::get_root::<Monster>(buf);
}

#[inline]
pub fn MonsterIdentifier() -> &'static str {
  return "MONS";
}

#[inline]
pub fn MonsterBufferHasIdentifier(buf: &[u8]) -> bool {
  return flatbuffers::buffer_has_identifier(
      buf, MonsterIdentifier());
}

#[inline]
pub fn VerifyMonsterBuffer(
    verifier: &mut flatbuffers::Verifier) -> bool {
  return verifier.verify_buffer::<Monster>(MonsterIdentifier());
}

#[inline]
pub fn MonsterExtension() -> &'static str {
  return "mon";
}

#[inline]
pub fn FinishMonsterBuffer<'a: 'b, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::LabeledUOffsetT<MonsterOffset>) {
  fbb.finish_with_identifier(root, MonsterIdentifier());
}

}  // pub mod Example
}  // pub mod MyGame

