// automatically generated by the FlatBuffers compiler, do not modify



pub mod MyGame {
  #[allow(unused_imports)]
  use std::mem;
  #[allow(unused_imports)]
  use std::marker::PhantomData;
  #[allow(unused_imports)]
  #[allow(unreachable_code)]
  extern crate flatbuffers;
  #[allow(unused_imports)]
  use self::flatbuffers::flexbuffers;
  #[allow(unused_imports)]
  use std::cmp::Ordering;

pub enum InParentNamespaceOffset {}
pub struct InParentNamespace<'a> {
  pub _tab: flatbuffers::Table<'a>,
  _phantom: PhantomData<&'a ()>,
}
// impl<'a> flatbuffers::Table for InParentNamespace<'a> {
//impl<'a> flatbuffers::BufferBacked<'a> for InParentNamespace<'a> {
impl<'a> flatbuffers::BufferBacked<'a> for InParentNamespace<'a> {
    fn init_from_bytes(bytes: &'a [u8], pos: usize) -> Self {
        InParentNamespace {
            _tab: flatbuffers::Table {
                data: bytes,
                pos: pos,
            },
            _phantom: PhantomData,
        }
    }
}
impl<'a> InParentNamespace<'a> /* private flatbuffers::Table */ {
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        InParentNamespace {
            _tab: table,
            _phantom: PhantomData,
        }
    }
}

pub struct InParentNamespaceArgs<'a> {
    pub _phantom: PhantomData<&'a ()>, // pub for default trait
}
impl<'a> Default for InParentNamespaceArgs<'a> {
    fn default() -> Self {
        InParentNamespaceArgs {
            _phantom: PhantomData,
        }
    }
}
pub struct InParentNamespaceBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::LabeledUOffsetT<flatbuffers::TableOffset>,
}
impl<'a: 'b, 'b> InParentNamespaceBuilder<'a, 'b> {
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> InParentNamespaceBuilder<'a, 'b> {
    let start = _fbb.start_table(0);
    InParentNamespaceBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  // InParentNamespaceBuilder &operator=(const InParentNamespaceBuilder &);
  //pub fn finish<'c>(mut self) -> flatbuffers::LabeledUOffsetT<flatbuffers::TableOffset> {
  pub fn finish<'c>(mut self) -> flatbuffers::LabeledUOffsetT<InParentNamespaceOffset> {
    let o = self.fbb_.end_table(self.start_);
    //let o = flatbuffers::LabeledUOffsetT::<InParentNamespaceOffset>::new(end);
    flatbuffers::LabeledUOffsetT::new(o.value())
  }
}

#[inline]
pub fn CreateInParentNamespace<'a: 'b, 'b>(
    _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    args: &InParentNamespaceArgs) -> flatbuffers::LabeledUOffsetT<InParentNamespaceOffset> {
  let mut builder = InParentNamespaceBuilder::new(_fbb);
  builder.finish()
}

pub mod Example2 {
  #[allow(unused_imports)]
  use std::mem;
  #[allow(unused_imports)]
  use std::marker::PhantomData;
  #[allow(unused_imports)]
  #[allow(unreachable_code)]
  extern crate flatbuffers;
  #[allow(unused_imports)]
  use self::flatbuffers::flexbuffers;
  #[allow(unused_imports)]
  use std::cmp::Ordering;

pub enum MonsterOffset {}
pub struct Monster<'a> {
  pub _tab: flatbuffers::Table<'a>,
  _phantom: PhantomData<&'a ()>,
}
// impl<'a> flatbuffers::Table for Monster<'a> {
//impl<'a> flatbuffers::BufferBacked<'a> for Monster<'a> {
impl<'a> flatbuffers::BufferBacked<'a> for Monster<'a> {
    fn init_from_bytes(bytes: &'a [u8], pos: usize) -> Self {
        Monster {
            _tab: flatbuffers::Table {
                data: bytes,
                pos: pos,
            },
            _phantom: PhantomData,
        }
    }
}
impl<'a> Monster<'a> /* private flatbuffers::Table */ {
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        Monster {
            _tab: table,
            _phantom: PhantomData,
        }
    }
}

pub struct MonsterArgs<'a> {
    pub _phantom: PhantomData<&'a ()>, // pub for default trait
}
impl<'a> Default for MonsterArgs<'a> {
    fn default() -> Self {
        MonsterArgs {
            _phantom: PhantomData,
        }
    }
}
pub struct MonsterBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::LabeledUOffsetT<flatbuffers::TableOffset>,
}
impl<'a: 'b, 'b> MonsterBuilder<'a, 'b> {
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> MonsterBuilder<'a, 'b> {
    let start = _fbb.start_table(0);
    MonsterBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  // MonsterBuilder &operator=(const MonsterBuilder &);
  //pub fn finish<'c>(mut self) -> flatbuffers::LabeledUOffsetT<flatbuffers::TableOffset> {
  pub fn finish<'c>(mut self) -> flatbuffers::LabeledUOffsetT<MonsterOffset> {
    let o = self.fbb_.end_table(self.start_);
    //let o = flatbuffers::LabeledUOffsetT::<MonsterOffset>::new(end);
    flatbuffers::LabeledUOffsetT::new(o.value())
  }
}

#[inline]
pub fn CreateMonster<'a: 'b, 'b>(
    _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    args: &MonsterArgs) -> flatbuffers::LabeledUOffsetT<MonsterOffset> {
  let mut builder = MonsterBuilder::new(_fbb);
  builder.finish()
}

}  // pub mod Example2

pub mod Example {
  #[allow(unused_imports)]
  use std::mem;
  #[allow(unused_imports)]
  use std::marker::PhantomData;
  #[allow(unused_imports)]
  #[allow(unreachable_code)]
  extern crate flatbuffers;
  #[allow(unused_imports)]
  use self::flatbuffers::flexbuffers;
  #[allow(unused_imports)]
  use std::cmp::Ordering;

#[repr(i8)]
#[derive(Clone, Copy, PartialEq, Debug)]
pub enum Color {
  Red = 1,
  Green = 2,
  Blue = 8
}

const EnumValuesColor:[Color; 3] = [
  Color::Red,
  Color::Green,
  Color::Blue
];

const EnumNamesColor:[&'static str; 8] = [
    "Red",
    "Green",
    "",
    "",
    "",
    "",
    "",
    "Blue"
];

pub fn EnumNameColor(e: Color) -> &'static str {
  let index: usize = e as usize - Color::Red as usize;
  EnumNamesColor[index]
}

#[repr(u8)]
#[derive(Clone, Copy, PartialEq, Debug)]
pub enum Any {
  NONE = 0,
  Monster = 1,
  TestSimpleTableWithEnum = 2,
  MyGame_Example2_Monster = 3
}

const EnumValuesAny:[Any; 4] = [
  Any::NONE,
  Any::Monster,
  Any::TestSimpleTableWithEnum,
  Any::MyGame_Example2_Monster
];

const EnumNamesAny:[&'static str; 4] = [
    "NONE",
    "Monster",
    "TestSimpleTableWithEnum",
    "MyGame_Example2_Monster"
];

pub fn EnumNameAny(e: Any) -> &'static str {
  let index: usize = e as usize;
  EnumNamesAny[index]
}

// MANUALLY_ALIGNED_STRUCT(2)
#[repr(C, packed)]
#[derive(Clone, Copy, Default, Debug)]
pub struct Test {
  a_: i16,
  b_: i8,
  padding0__: u8,
} // pub struct Test
impl flatbuffers::GeneratedStruct for Test {}

impl Test {
  pub fn Reset(&mut self) {
    //memset(this, 0, size_of(Test));
  }
  pub fn new(_a: i16, _b: i8) -> Self {
    Test {
      a_: flatbuffers::endian_scalar(_a),
      b_: flatbuffers::endian_scalar(_b),


        padding0__: 0,
    }
  }
  pub fn a(&self) -> i16  {
    flatbuffers::endian_scalar(self.a_)
  }
  pub fn b(&self) -> i8  {
    flatbuffers::endian_scalar(self.b_)
  }
}
// STRUCT_END(Test, 4);

// MANUALLY_ALIGNED_STRUCT(16)
#[repr(C, packed)]
#[derive(Clone, Copy, Default, Debug)]
pub struct Vec3 {
  x_: f32,
  y_: f32,
  z_: f32,
  padding0__: u32,
  test1_: f64,
  test2_: i8,
  padding1__: u8,
  test3_: Test/* foo */,
  padding2__: u16,
} // pub struct Vec3
impl flatbuffers::GeneratedStruct for Vec3 {}

impl Vec3 {
  pub fn Reset(&mut self) {
    //memset(this, 0, size_of(Vec3));
  }
  pub fn new(_x: f32, _y: f32, _z: f32, _test1: f64, _test2: Color, _test3: Test/* foo */) -> Self {
    Vec3 {
      x_: _x,
      y_: _y,
      z_: _z,
      test1_: _test1,
      test2_: flatbuffers::endian_scalar(_test2 as i8),
      test3_: _test3,


        padding0__: 0,

        padding1__: 0,

        padding2__: 0,
    }
  }
  pub fn x(&self) -> f32  {
    self.x_
  }
  pub fn y(&self) -> f32  {
    self.y_
  }
  pub fn z(&self) -> f32  {
    self.z_
  }
  pub fn test1(&self) -> f64  {
    self.test1_
  }
  pub fn test2(&self) -> Color  {
    unsafe { ::std::mem::transmute(flatbuffers::endian_scalar(self.test2_)) }
  }
  pub fn test3(&self) -> &Test/* foo */ {
    &self.test3_
  }
}
// STRUCT_END(Vec3, 32);

// MANUALLY_ALIGNED_STRUCT(4)
#[repr(C, packed)]
#[derive(Clone, Copy, Default, Debug)]
pub struct Ability {
  id_: u32,
  distance_: u32,
} // pub struct Ability
impl flatbuffers::GeneratedStruct for Ability {}

impl Ability {
  pub fn Reset(&mut self) {
    //memset(this, 0, size_of(Ability));
  }
  pub fn new(_id: u32, _distance: u32) -> Self {
    Ability {
      id_: flatbuffers::endian_scalar(_id),
      distance_: flatbuffers::endian_scalar(_distance),

    }
  }
  pub fn id(&self) -> u32  {
    flatbuffers::endian_scalar(self.id_)
  }
  fn KeyCompareLessThan(&self, o: &Ability) -> bool {
    unimplemented!();
    //self.id() < o.id()
  }
  fn KeyCompareWithValue(&self, val: u32) -> isize {
    let key = self.id();
    (key > val) as isize - (key < val) as isize
  }
  pub fn distance(&self) -> u32  {
    flatbuffers::endian_scalar(self.distance_)
  }
}
// STRUCT_END(Ability, 8);

pub enum TestSimpleTableWithEnumOffset {}
pub struct TestSimpleTableWithEnum<'a> {
  pub _tab: flatbuffers::Table<'a>,
  _phantom: PhantomData<&'a ()>,
}
// impl<'a> flatbuffers::Table for TestSimpleTableWithEnum<'a> {
//impl<'a> flatbuffers::BufferBacked<'a> for TestSimpleTableWithEnum<'a> {
impl<'a> flatbuffers::BufferBacked<'a> for TestSimpleTableWithEnum<'a> {
    fn init_from_bytes(bytes: &'a [u8], pos: usize) -> Self {
        TestSimpleTableWithEnum {
            _tab: flatbuffers::Table {
                data: bytes,
                pos: pos,
            },
            _phantom: PhantomData,
        }
    }
}
impl<'a> TestSimpleTableWithEnum<'a> /* private flatbuffers::Table */ {
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        TestSimpleTableWithEnum {
            _tab: table,
            _phantom: PhantomData,
        }
    }
    pub const VT_COLOR: flatbuffers::VOffsetT = 4;

  pub fn color(&'a self) -> Color  {
    unsafe { ::std::mem::transmute(self._tab.get_slot_scalar::<i8>(TestSimpleTableWithEnum::VT_COLOR, 2)) }
  }
}

pub struct TestSimpleTableWithEnumArgs<'a> {
    pub color: Option<Color>,
    pub _phantom: PhantomData<&'a ()>, // pub for default trait
}
impl<'a> Default for TestSimpleTableWithEnumArgs<'a> {
    fn default() -> Self {
        TestSimpleTableWithEnumArgs {
            color: None,
            _phantom: PhantomData,
        }
    }
}
pub struct TestSimpleTableWithEnumBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::LabeledUOffsetT<flatbuffers::TableOffset>,
}
impl<'a: 'b, 'b> TestSimpleTableWithEnumBuilder<'a, 'b> {
  pub fn add_color(&mut self, color: Color ) {
    self.fbb_.push_slot_scalar::<i8>(TestSimpleTableWithEnum::VT_COLOR, color as i8, 2);
  }
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> TestSimpleTableWithEnumBuilder<'a, 'b> {
    let start = _fbb.start_table(1);
    TestSimpleTableWithEnumBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  // TestSimpleTableWithEnumBuilder &operator=(const TestSimpleTableWithEnumBuilder &);
  //pub fn finish<'c>(mut self) -> flatbuffers::LabeledUOffsetT<flatbuffers::TableOffset> {
  pub fn finish<'c>(mut self) -> flatbuffers::LabeledUOffsetT<TestSimpleTableWithEnumOffset> {
    let o = self.fbb_.end_table(self.start_);
    //let o = flatbuffers::LabeledUOffsetT::<TestSimpleTableWithEnumOffset>::new(end);
    flatbuffers::LabeledUOffsetT::new(o.value())
  }
}

#[inline]
pub fn CreateTestSimpleTableWithEnum<'a: 'b, 'b>(
    _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    args: &TestSimpleTableWithEnumArgs) -> flatbuffers::LabeledUOffsetT<TestSimpleTableWithEnumOffset> {
  let mut builder = TestSimpleTableWithEnumBuilder::new(_fbb);
  if let Some(x) = args.color { builder.add_color(x); }
  builder.finish()
}

pub enum StatOffset {}
pub struct Stat<'a> {
  pub _tab: flatbuffers::Table<'a>,
  _phantom: PhantomData<&'a ()>,
}
// impl<'a> flatbuffers::Table for Stat<'a> {
//impl<'a> flatbuffers::BufferBacked<'a> for Stat<'a> {
impl<'a> flatbuffers::BufferBacked<'a> for Stat<'a> {
    fn init_from_bytes(bytes: &'a [u8], pos: usize) -> Self {
        Stat {
            _tab: flatbuffers::Table {
                data: bytes,
                pos: pos,
            },
            _phantom: PhantomData,
        }
    }
}
impl<'a> Stat<'a> /* private flatbuffers::Table */ {
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        Stat {
            _tab: table,
            _phantom: PhantomData,
        }
    }
    pub const VT_ID: flatbuffers::VOffsetT = 4;
    pub const VT_VAL: flatbuffers::VOffsetT = 6;
    pub const VT_COUNT: flatbuffers::VOffsetT = 8;

  pub fn id(&'a self) -> Option<&str> {
    self._tab.get_slot_string_unsafe(Stat::VT_ID)
  }
  pub fn val(&'a self) -> i64  {
    self._tab.get_slot_scalar::<i64>(Stat::VT_VAL, 0)
  }
  pub fn count(&'a self) -> u16  {
    self._tab.get_slot_scalar::<u16>(Stat::VT_COUNT, 0)
  }
}

pub struct StatArgs<'a> {
    pub id: Option<StringOffset>,
    pub val: Option<i64>,
    pub count: Option<u16>,
    pub _phantom: PhantomData<&'a ()>, // pub for default trait
}
impl<'a> Default for StatArgs<'a> {
    fn default() -> Self {
        StatArgs {
            id: None,
            val: None,
            count: None,
            _phantom: PhantomData,
        }
    }
}
pub struct StatBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::LabeledUOffsetT<flatbuffers::TableOffset>,
}
impl<'a: 'b, 'b> StatBuilder<'a, 'b> {
  pub fn add_id(&mut self, id: flatbuffers::LabeledUOffsetT<flatbuffers::StringOffset> ) {
    self.fbb_.push_slot_labeled_uoffset_relative(Stat::VT_ID, id);
  }
  pub fn add_val(&mut self, val: i64 ) {
    self.fbb_.push_slot_scalar::<i64>(Stat::VT_VAL, val, 0);
  }
  pub fn add_count(&mut self, count: u16 ) {
    self.fbb_.push_slot_scalar::<u16>(Stat::VT_COUNT, count, 0);
  }
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> StatBuilder<'a, 'b> {
    let start = _fbb.start_table(3);
    StatBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  // StatBuilder &operator=(const StatBuilder &);
  //pub fn finish<'c>(mut self) -> flatbuffers::LabeledUOffsetT<flatbuffers::TableOffset> {
  pub fn finish<'c>(mut self) -> flatbuffers::LabeledUOffsetT<StatOffset> {
    let o = self.fbb_.end_table(self.start_);
    //let o = flatbuffers::LabeledUOffsetT::<StatOffset>::new(end);
    flatbuffers::LabeledUOffsetT::new(o.value())
  }
}

#[inline]
pub fn CreateStat<'a: 'b, 'b>(
    _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    args: &StatArgs) -> flatbuffers::LabeledUOffsetT<StatOffset> {
  let mut builder = StatBuilder::new(_fbb);
  if let Some(x) = args.val { builder.add_val(x); }
  if let Some(x) = args.id { builder.add_id(x); }
  if let Some(x) = args.count { builder.add_count(x); }
  builder.finish()
}

/// an example documentation comment: monster object
pub enum MonsterOffset {}
pub struct Monster<'a> {
  pub _tab: flatbuffers::Table<'a>,
  _phantom: PhantomData<&'a ()>,
}
// impl<'a> flatbuffers::Table for Monster<'a> {
//impl<'a> flatbuffers::BufferBacked<'a> for Monster<'a> {
impl<'a> flatbuffers::BufferBacked<'a> for Monster<'a> {
    fn init_from_bytes(bytes: &'a [u8], pos: usize) -> Self {
        Monster {
            _tab: flatbuffers::Table {
                data: bytes,
                pos: pos,
            },
            _phantom: PhantomData,
        }
    }
}
impl<'a> Monster<'a> /* private flatbuffers::Table */ {
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        Monster {
            _tab: table,
            _phantom: PhantomData,
        }
    }
    pub const VT_POS: flatbuffers::VOffsetT = 4;
    pub const VT_MANA: flatbuffers::VOffsetT = 6;
    pub const VT_HP: flatbuffers::VOffsetT = 8;
    pub const VT_NAME: flatbuffers::VOffsetT = 10;
    pub const VT_INVENTORY: flatbuffers::VOffsetT = 14;
    pub const VT_COLOR: flatbuffers::VOffsetT = 16;
    pub const VT_TEST_TYPE: flatbuffers::VOffsetT = 18;
    pub const VT_TEST: flatbuffers::VOffsetT = 20;
    pub const VT_TEST4: flatbuffers::VOffsetT = 22;
    pub const VT_TESTARRAYOFSTRING: flatbuffers::VOffsetT = 24;
    pub const VT_TESTARRAYOFTABLES: flatbuffers::VOffsetT = 26;
    pub const VT_ENEMY: flatbuffers::VOffsetT = 28;
    pub const VT_TESTNESTEDFLATBUFFER: flatbuffers::VOffsetT = 30;
    pub const VT_TESTEMPTY: flatbuffers::VOffsetT = 32;
    pub const VT_TESTBOOL: flatbuffers::VOffsetT = 34;
    pub const VT_TESTHASHS32_FNV1: flatbuffers::VOffsetT = 36;
    pub const VT_TESTHASHU32_FNV1: flatbuffers::VOffsetT = 38;
    pub const VT_TESTHASHS64_FNV1: flatbuffers::VOffsetT = 40;
    pub const VT_TESTHASHU64_FNV1: flatbuffers::VOffsetT = 42;
    pub const VT_TESTHASHS32_FNV1A: flatbuffers::VOffsetT = 44;
    pub const VT_TESTHASHU32_FNV1A: flatbuffers::VOffsetT = 46;
    pub const VT_TESTHASHS64_FNV1A: flatbuffers::VOffsetT = 48;
    pub const VT_TESTHASHU64_FNV1A: flatbuffers::VOffsetT = 50;
    pub const VT_TESTARRAYOFBOOLS: flatbuffers::VOffsetT = 52;
    pub const VT_TESTF: flatbuffers::VOffsetT = 54;
    pub const VT_TESTF2: flatbuffers::VOffsetT = 56;
    pub const VT_TESTF3: flatbuffers::VOffsetT = 58;
    pub const VT_TESTARRAYOFSTRING2: flatbuffers::VOffsetT = 60;
    pub const VT_TESTARRAYOFSORTEDSTRUCT: flatbuffers::VOffsetT = 62;
    pub const VT_FLEX: flatbuffers::VOffsetT = 64;
    pub const VT_TEST5: flatbuffers::VOffsetT = 66;
    pub const VT_VECTOR_OF_LONGS: flatbuffers::VOffsetT = 68;
    pub const VT_VECTOR_OF_DOUBLES: flatbuffers::VOffsetT = 70;
    pub const VT_PARENT_NAMESPACE_TEST: flatbuffers::VOffsetT = 72;

  pub fn pos(&'a self) -> Option<&Vec3/* foo */ > {
    self._tab.get_struct_unsafe::<Vec3/* foo */>(Monster::VT_POS)
  }
  pub fn mana(&'a self) -> i16  {
    self._tab.get_slot_scalar::<i16>(Monster::VT_MANA, 150)
  }
  pub fn hp(&'a self) -> i16  {
    self._tab.get_slot_scalar::<i16>(Monster::VT_HP, 100)
  }
  pub fn name(&'a self) -> Option<&str> {
    self._tab.get_slot_string_unsafe(Monster::VT_NAME)
  }
  fn KeyCompareLessThan(&self, o: &Monster) -> bool {
    unimplemented!()
    //return *self.name() < *o.name();
  }
  fn KeyCompareWithValue(&self, _val: &str) -> Ordering {
    unimplemented!();
    Ordering::Equal
    // TODO(rw): self.name().cmp(val)
  }
  pub fn inventory(&'a self) -> Option< &'a[u8] > {
    self._tab.get_slot_vector::<u8>(Monster::VT_INVENTORY)
  }
  pub fn color(&'a self) -> Color  {
    unsafe { ::std::mem::transmute(self._tab.get_slot_scalar::<i8>(Monster::VT_COLOR, 8)) }
  }
  pub fn test_type(&'a self) -> Any  {
    unsafe { ::std::mem::transmute(self._tab.get_slot_scalar::<u8>(Monster::VT_TEST_TYPE, 0)) }
  }
  pub fn test(&'a self) -> Option<flatbuffers::Table> {
    self._tab.get_slot_union(Monster::VT_TEST)
  }
  // TODO(?) template<typename T> const T *test_as() const;
  // TODO: fn test_as_Monster() -> &Monster {
// TODO:     if test_type() == Any::Monster { static_cast::<&Monster>(test()) } else { nullptr }
// TODO:   }
  // TODO: fn test_as_TestSimpleTableWithEnum() -> &TestSimpleTableWithEnum {
// TODO:     if test_type() == Any::TestSimpleTableWithEnum { static_cast::<&TestSimpleTableWithEnum>(test()) } else { nullptr }
// TODO:   }
  // TODO: fn test_as_MyGame_Example2_Monster() -> &super::Example2::Monster {
// TODO:     if test_type() == Any::MyGame_Example2_Monster { static_cast::<&super::Example2::Monster>(test()) } else { nullptr }
// TODO:   }
  pub fn test4(&'a self) -> Option< &'a[Test/* foo */] > {
    self._tab.get_slot_vector::<Test/* foo */>(Monster::VT_TEST4)
  }
  pub fn testarrayofstring(&'a self) -> Option< &'a[flatbuffers::LabeledUOffsetT<flatbuffers::StringOffset>] > {
    self._tab.get_slot_vector::<flatbuffers::LabeledUOffsetT<flatbuffers::StringOffset>>(Monster::VT_TESTARRAYOFSTRING)
  }
  /// an example documentation comment: this will end up in the generated code
  /// multiline too
  pub fn testarrayoftables(&'a self) -> Option< &'a[flatbuffers::LabeledUOffsetT<Monster<'a>>] > {
    self._tab.get_slot_vector::<flatbuffers::LabeledUOffsetT<Monster<>>>(Monster::VT_TESTARRAYOFTABLES)
  }
  pub fn enemy(&'a self) -> &Monster<'a>  {
    flatbuffers::get_pointer::<&Monster<'a>>(Monster::VT_ENEMY)
  }
  pub fn testnestedflatbuffer(&'a self) -> Option< &'a[u8] > {
    self._tab.get_slot_vector::<u8>(Monster::VT_TESTNESTEDFLATBUFFER)
  }
//TODO: mutable nested root
  fn testnestedflatbuffer_nested_root(&self) -> &Monster{
    unimplemented!()
    // TODO(rw): return flatbuffers::get_root::<Monster>(self.testnestedflatbuffer().Data());
  }
  pub fn testempty(&'a self) -> &Stat<'a>  {
    flatbuffers::get_pointer::<&Stat<'a>>(Monster::VT_TESTEMPTY)
  }
  pub fn testbool(&'a self) -> bool  {
    self._tab.get_slot_scalar::<u8>(Monster::VT_TESTBOOL, 0) != 0
  }
  pub fn testhashs32_fnv1(&'a self) -> i32  {
    self._tab.get_slot_scalar::<i32>(Monster::VT_TESTHASHS32_FNV1, 0)
  }
  pub fn testhashu32_fnv1(&'a self) -> u32  {
    self._tab.get_slot_scalar::<u32>(Monster::VT_TESTHASHU32_FNV1, 0)
  }
  pub fn testhashs64_fnv1(&'a self) -> i64  {
    self._tab.get_slot_scalar::<i64>(Monster::VT_TESTHASHS64_FNV1, 0)
  }
  pub fn testhashu64_fnv1(&'a self) -> u64  {
    self._tab.get_slot_scalar::<u64>(Monster::VT_TESTHASHU64_FNV1, 0)
  }
  pub fn testhashs32_fnv1a(&'a self) -> i32  {
    self._tab.get_slot_scalar::<i32>(Monster::VT_TESTHASHS32_FNV1A, 0)
  }
  pub fn testhashu32_fnv1a(&'a self) -> u32  {
    self._tab.get_slot_scalar::<u32>(Monster::VT_TESTHASHU32_FNV1A, 0)
  }
  pub fn testhashs64_fnv1a(&'a self) -> i64  {
    self._tab.get_slot_scalar::<i64>(Monster::VT_TESTHASHS64_FNV1A, 0)
  }
  pub fn testhashu64_fnv1a(&'a self) -> u64  {
    self._tab.get_slot_scalar::<u64>(Monster::VT_TESTHASHU64_FNV1A, 0)
  }
  pub fn testarrayofbools(&'a self) -> Option< &'a[u8] > {
    self._tab.get_slot_vector::<u8>(Monster::VT_TESTARRAYOFBOOLS)
  }
  pub fn testf(&'a self) -> f32  {
    self._tab.get_slot_scalar::<f32>(Monster::VT_TESTF, 3.14159)
  }
  pub fn testf2(&'a self) -> f32  {
    self._tab.get_slot_scalar::<f32>(Monster::VT_TESTF2, 3.0)
  }
  pub fn testf3(&'a self) -> f32  {
    self._tab.get_slot_scalar::<f32>(Monster::VT_TESTF3, 0.0)
  }
  pub fn testarrayofstring2(&'a self) -> Option< &'a[flatbuffers::LabeledUOffsetT<flatbuffers::StringOffset>] > {
    self._tab.get_slot_vector::<flatbuffers::LabeledUOffsetT<flatbuffers::StringOffset>>(Monster::VT_TESTARRAYOFSTRING2)
  }
  pub fn testarrayofsortedstruct(&'a self) -> Option< &'a[Ability/* foo */] > {
    self._tab.get_slot_vector::<Ability/* foo */>(Monster::VT_TESTARRAYOFSORTEDSTRUCT)
  }
  pub fn flex(&'a self) -> Option< &'a[u8] > {
    self._tab.get_slot_vector::<u8>(Monster::VT_FLEX)
  }
  pub fn test5(&'a self) -> Option< &'a[Test/* foo */] > {
    self._tab.get_slot_vector::<Test/* foo */>(Monster::VT_TEST5)
  }
  pub fn vector_of_longs(&'a self) -> Option< &'a[i64] > {
    self._tab.get_slot_vector::<i64>(Monster::VT_VECTOR_OF_LONGS)
  }
  pub fn vector_of_doubles(&'a self) -> Option< &'a[f64] > {
    self._tab.get_slot_vector::<f64>(Monster::VT_VECTOR_OF_DOUBLES)
  }
  pub fn parent_namespace_test(&'a self) -> &super::InParentNamespace<'a>  {
    flatbuffers::get_pointer::<&super::InParentNamespace<'a>>(Monster::VT_PARENT_NAMESPACE_TEST)
  }
}

//TODO: inject these functions into impl for type
//#[inline]
//fn Monster_MEMBER_test_as_X_Monster_X() -> &Monster {
//  return test_as_Monster();
//}
//
//TODO: inject these functions into impl for type
//#[inline]
//fn Monster_MEMBER_test_as_X_TestSimpleTableWithEnum_X() -> &TestSimpleTableWithEnum {
//  return test_as_TestSimpleTableWithEnum();
//}
//
//TODO: inject these functions into impl for type
//#[inline]
//fn Monster_MEMBER_test_as_X_super::Example2::Monster_X() -> &super::Example2::Monster {
//  return test_as_MyGame_Example2_Monster();
//}
//
pub struct MonsterArgs<'a> {
    pub pos: Option<&'a Vec3>,
    pub mana: Option<i16>,
    pub hp: Option<i16>,
    pub name: Option<StringOffset>,
    pub inventory: Option<flatbuffers::VectorLabeledUOffsetT<VectorOffset>>,
    pub color: Option<Color>,
    pub test_type: Option<Any>,
    pub test: Option<Any>,
    pub test4: Option<flatbuffers::VectorLabeledUOffsetT<&'a Test>>,
    pub testarrayofstring: Option<flatbuffers::VectorLabeledUOffsetT<StringOffset>>,
    pub testarrayoftables: Option<flatbuffers::VectorLabeledUOffsetT<MonsterOffset>>,
    pub enemy: Option<MonsterOffset>,
    pub testnestedflatbuffer: Option<flatbuffers::VectorLabeledUOffsetT<VectorOffset>>,
    pub testempty: Option<StatOffset>,
    pub testbool: Option<bool>,
    pub testhashs32_fnv1: Option<i32>,
    pub testhashu32_fnv1: Option<u32>,
    pub testhashs64_fnv1: Option<i64>,
    pub testhashu64_fnv1: Option<u64>,
    pub testhashs32_fnv1a: Option<i32>,
    pub testhashu32_fnv1a: Option<u32>,
    pub testhashs64_fnv1a: Option<i64>,
    pub testhashu64_fnv1a: Option<u64>,
    pub testarrayofbools: Option<flatbuffers::VectorLabeledUOffsetT<bool>>,
    pub testf: Option<f32>,
    pub testf2: Option<f32>,
    pub testf3: Option<f32>,
    pub testarrayofstring2: Option<flatbuffers::VectorLabeledUOffsetT<StringOffset>>,
    pub testarrayofsortedstruct: Option<flatbuffers::VectorLabeledUOffsetT<&'a Ability>>,
    pub flex: Option<flatbuffers::VectorLabeledUOffsetT<VectorOffset>>,
    pub test5: Option<flatbuffers::VectorLabeledUOffsetT<&'a Test>>,
    pub vector_of_longs: Option<flatbuffers::VectorLabeledUOffsetT<VectorOffset>>,
    pub vector_of_doubles: Option<flatbuffers::VectorLabeledUOffsetT<VectorOffset>>,
    pub parent_namespace_test: Option<MyGame::InParentNamespaceOffset>,
    pub _phantom: PhantomData<&'a ()>, // pub for default trait
}
impl<'a> Default for MonsterArgs<'a> {
    fn default() -> Self {
        MonsterArgs {
            pos: None,
            mana: None,
            hp: None,
 // required
            name: None,
            inventory: None,
            color: None,
            test_type: None,
            test: None,
            test4: None,
            testarrayofstring: None,
            testarrayoftables: None,
            enemy: None,
            testnestedflatbuffer: None,
            testempty: None,
            testbool: None,
            testhashs32_fnv1: None,
            testhashu32_fnv1: None,
            testhashs64_fnv1: None,
            testhashu64_fnv1: None,
            testhashs32_fnv1a: None,
            testhashu32_fnv1a: None,
            testhashs64_fnv1a: None,
            testhashu64_fnv1a: None,
            testarrayofbools: None,
            testf: None,
            testf2: None,
            testf3: None,
            testarrayofstring2: None,
            testarrayofsortedstruct: None,
            flex: None,
            test5: None,
            vector_of_longs: None,
            vector_of_doubles: None,
            parent_namespace_test: None,
            _phantom: PhantomData,
        }
    }
}
pub struct MonsterBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::LabeledUOffsetT<flatbuffers::TableOffset>,
}
impl<'a: 'b, 'b> MonsterBuilder<'a, 'b> {
  pub fn add_pos(&mut self, pos: Option<&Vec3/* foo */>) {
    self.fbb_.push_slot_struct::<Vec3/* foo */>(Monster::VT_POS, pos);
  }
  pub fn add_mana(&mut self, mana: i16 ) {
    self.fbb_.push_slot_scalar::<i16>(Monster::VT_MANA, mana, 150);
  }
  pub fn add_hp(&mut self, hp: i16 ) {
    self.fbb_.push_slot_scalar::<i16>(Monster::VT_HP, hp, 100);
  }
  pub fn add_name(&mut self, name: flatbuffers::LabeledUOffsetT<flatbuffers::StringOffset> ) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_NAME, name);
  }
  pub fn add_inventory(&mut self, inventory: flatbuffers::LabeledUOffsetT<&[u8]> ) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_INVENTORY, inventory);
  }
  pub fn add_color(&mut self, color: Color ) {
    self.fbb_.push_slot_scalar::<i8>(Monster::VT_COLOR, color as i8, 8);
  }
  pub fn add_test_type(&mut self, test_type: Any ) {
    self.fbb_.push_slot_scalar::<u8>(Monster::VT_TEST_TYPE, test_type as u8, 0);
  }
  pub fn add_test(&mut self, test: Option<flatbuffers::LabeledUOffsetT<flatbuffers::UnionOffset>> ) {
    self.fbb_.push_slot_labeled_uoffset_relative_from_option(Monster::VT_TEST, test);
  }
  pub fn add_test4(&mut self, test4: flatbuffers::LabeledUOffsetT<&[Test/* foo */]> ) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_TEST4, test4);
  }
  pub fn add_testarrayofstring(&mut self, testarrayofstring: flatbuffers::LabeledUOffsetT<&[flatbuffers::LabeledUOffsetT<flatbuffers::StringOffset>]> ) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_TESTARRAYOFSTRING, testarrayofstring);
  }
  pub fn add_testarrayoftables(&mut self, testarrayoftables: flatbuffers::LabeledUOffsetT<&[flatbuffers::LabeledUOffsetT<Monster<>>]> ) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_TESTARRAYOFTABLES, testarrayoftables);
  }
  pub fn add_enemy(&mut self, enemy: flatbuffers::LabeledUOffsetT<Monster<>> ) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_ENEMY, enemy);
  }
  pub fn add_testnestedflatbuffer(&mut self, testnestedflatbuffer: flatbuffers::LabeledUOffsetT<&[u8]> ) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_TESTNESTEDFLATBUFFER, testnestedflatbuffer);
  }
  pub fn add_testempty(&mut self, testempty: flatbuffers::LabeledUOffsetT<Stat<>> ) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_TESTEMPTY, testempty);
  }
  pub fn add_testbool(&mut self, testbool: bool ) {
    self.fbb_.push_slot_scalar::<u8>(Monster::VT_TESTBOOL, testbool as u8, 0);
  }
  pub fn add_testhashs32_fnv1(&mut self, testhashs32_fnv1: i32 ) {
    self.fbb_.push_slot_scalar::<i32>(Monster::VT_TESTHASHS32_FNV1, testhashs32_fnv1, 0);
  }
  pub fn add_testhashu32_fnv1(&mut self, testhashu32_fnv1: u32 ) {
    self.fbb_.push_slot_scalar::<u32>(Monster::VT_TESTHASHU32_FNV1, testhashu32_fnv1, 0);
  }
  pub fn add_testhashs64_fnv1(&mut self, testhashs64_fnv1: i64 ) {
    self.fbb_.push_slot_scalar::<i64>(Monster::VT_TESTHASHS64_FNV1, testhashs64_fnv1, 0);
  }
  pub fn add_testhashu64_fnv1(&mut self, testhashu64_fnv1: u64 ) {
    self.fbb_.push_slot_scalar::<u64>(Monster::VT_TESTHASHU64_FNV1, testhashu64_fnv1, 0);
  }
  pub fn add_testhashs32_fnv1a(&mut self, testhashs32_fnv1a: i32 ) {
    self.fbb_.push_slot_scalar::<i32>(Monster::VT_TESTHASHS32_FNV1A, testhashs32_fnv1a, 0);
  }
  pub fn add_testhashu32_fnv1a(&mut self, testhashu32_fnv1a: u32 ) {
    self.fbb_.push_slot_scalar::<u32>(Monster::VT_TESTHASHU32_FNV1A, testhashu32_fnv1a, 0);
  }
  pub fn add_testhashs64_fnv1a(&mut self, testhashs64_fnv1a: i64 ) {
    self.fbb_.push_slot_scalar::<i64>(Monster::VT_TESTHASHS64_FNV1A, testhashs64_fnv1a, 0);
  }
  pub fn add_testhashu64_fnv1a(&mut self, testhashu64_fnv1a: u64 ) {
    self.fbb_.push_slot_scalar::<u64>(Monster::VT_TESTHASHU64_FNV1A, testhashu64_fnv1a, 0);
  }
  pub fn add_testarrayofbools(&mut self, testarrayofbools: flatbuffers::LabeledUOffsetT<&[u8]> ) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_TESTARRAYOFBOOLS, testarrayofbools);
  }
  pub fn add_testf(&mut self, testf: f32 ) {
    self.fbb_.push_slot_scalar::<f32>(Monster::VT_TESTF, testf, 3.14159);
  }
  pub fn add_testf2(&mut self, testf2: f32 ) {
    self.fbb_.push_slot_scalar::<f32>(Monster::VT_TESTF2, testf2, 3.0);
  }
  pub fn add_testf3(&mut self, testf3: f32 ) {
    self.fbb_.push_slot_scalar::<f32>(Monster::VT_TESTF3, testf3, 0.0);
  }
  pub fn add_testarrayofstring2(&mut self, testarrayofstring2: flatbuffers::LabeledUOffsetT<&[flatbuffers::LabeledUOffsetT<flatbuffers::StringOffset>]> ) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_TESTARRAYOFSTRING2, testarrayofstring2);
  }
  pub fn add_testarrayofsortedstruct(&mut self, testarrayofsortedstruct: flatbuffers::LabeledUOffsetT<&[Ability/* foo */]> ) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_TESTARRAYOFSORTEDSTRUCT, testarrayofsortedstruct);
  }
  pub fn add_flex(&mut self, flex: flatbuffers::LabeledUOffsetT<&[u8]> ) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_FLEX, flex);
  }
  pub fn add_test5(&mut self, test5: flatbuffers::LabeledUOffsetT<&[Test/* foo */]> ) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_TEST5, test5);
  }
  pub fn add_vector_of_longs(&mut self, vector_of_longs: flatbuffers::LabeledUOffsetT<&[i64]> ) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_VECTOR_OF_LONGS, vector_of_longs);
  }
  pub fn add_vector_of_doubles(&mut self, vector_of_doubles: flatbuffers::LabeledUOffsetT<&[f64]> ) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_VECTOR_OF_DOUBLES, vector_of_doubles);
  }
  pub fn add_parent_namespace_test(&mut self, parent_namespace_test: flatbuffers::LabeledUOffsetT<super::InParentNamespace<>> ) {
    self.fbb_.push_slot_labeled_uoffset_relative(Monster::VT_PARENT_NAMESPACE_TEST, parent_namespace_test);
  }
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> MonsterBuilder<'a, 'b> {
    let start = _fbb.start_table(35);
    MonsterBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  // MonsterBuilder &operator=(const MonsterBuilder &);
  //pub fn finish<'c>(mut self) -> flatbuffers::LabeledUOffsetT<flatbuffers::TableOffset> {
  pub fn finish<'c>(mut self) -> flatbuffers::LabeledUOffsetT<MonsterOffset> {
    let o = self.fbb_.end_table(self.start_);
    //let o = flatbuffers::LabeledUOffsetT::<MonsterOffset>::new(end);
    self.fbb_.required(&o, Monster::VT_NAME);
    flatbuffers::LabeledUOffsetT::new(o.value())
  }
}

#[inline]
pub fn CreateMonster<'a: 'b, 'b>(
    _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    args: &MonsterArgs) -> flatbuffers::LabeledUOffsetT<MonsterOffset> {
  let mut builder = MonsterBuilder::new(_fbb);
  if let Some(x) = args.testhashu64_fnv1a { builder.add_testhashu64_fnv1a(x); }
  if let Some(x) = args.testhashs64_fnv1a { builder.add_testhashs64_fnv1a(x); }
  if let Some(x) = args.testhashu64_fnv1 { builder.add_testhashu64_fnv1(x); }
  if let Some(x) = args.testhashs64_fnv1 { builder.add_testhashs64_fnv1(x); }
  if let Some(x) = args.parent_namespace_test { builder.add_parent_namespace_test(x); }
  if let Some(x) = args.vector_of_doubles { builder.add_vector_of_doubles(x); }
  if let Some(x) = args.vector_of_longs { builder.add_vector_of_longs(x); }
  if let Some(x) = args.test5 { builder.add_test5(x); }
  if let Some(x) = args.flex { builder.add_flex(x); }
  if let Some(x) = args.testarrayofsortedstruct { builder.add_testarrayofsortedstruct(x); }
  if let Some(x) = args.testarrayofstring2 { builder.add_testarrayofstring2(x); }
  if let Some(x) = args.testf3 { builder.add_testf3(x); }
  if let Some(x) = args.testf2 { builder.add_testf2(x); }
  if let Some(x) = args.testf { builder.add_testf(x); }
  if let Some(x) = args.testarrayofbools { builder.add_testarrayofbools(x); }
  if let Some(x) = args.testhashu32_fnv1a { builder.add_testhashu32_fnv1a(x); }
  if let Some(x) = args.testhashs32_fnv1a { builder.add_testhashs32_fnv1a(x); }
  if let Some(x) = args.testhashu32_fnv1 { builder.add_testhashu32_fnv1(x); }
  if let Some(x) = args.testhashs32_fnv1 { builder.add_testhashs32_fnv1(x); }
  if let Some(x) = args.testempty { builder.add_testempty(x); }
  if let Some(x) = args.testnestedflatbuffer { builder.add_testnestedflatbuffer(x); }
  if let Some(x) = args.enemy { builder.add_enemy(x); }
  if let Some(x) = args.testarrayoftables { builder.add_testarrayoftables(x); }
  if let Some(x) = args.testarrayofstring { builder.add_testarrayofstring(x); }
  if let Some(x) = args.test4 { builder.add_test4(x); }
  if let Some(x) = args.test { builder.add_test(x); }
  if let Some(x) = args.inventory { builder.add_inventory(x); }
  if let Some(x) = args.name { builder.add_name(x); }
  if let Some(x) = args.pos { builder.add_pos(x); }
  if let Some(x) = args.hp { builder.add_hp(x); }
  if let Some(x) = args.mana { builder.add_mana(x); }
  if let Some(x) = args.testbool { builder.add_testbool(x); }
  if let Some(x) = args.test_type { builder.add_test_type(x); }
  if let Some(x) = args.color { builder.add_color(x); }
  builder.finish()
}

pub enum TypeAliasesOffset {}
pub struct TypeAliases<'a> {
  pub _tab: flatbuffers::Table<'a>,
  _phantom: PhantomData<&'a ()>,
}
// impl<'a> flatbuffers::Table for TypeAliases<'a> {
//impl<'a> flatbuffers::BufferBacked<'a> for TypeAliases<'a> {
impl<'a> flatbuffers::BufferBacked<'a> for TypeAliases<'a> {
    fn init_from_bytes(bytes: &'a [u8], pos: usize) -> Self {
        TypeAliases {
            _tab: flatbuffers::Table {
                data: bytes,
                pos: pos,
            },
            _phantom: PhantomData,
        }
    }
}
impl<'a> TypeAliases<'a> /* private flatbuffers::Table */ {
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        TypeAliases {
            _tab: table,
            _phantom: PhantomData,
        }
    }
    pub const VT_I8_: flatbuffers::VOffsetT = 4;
    pub const VT_U8_: flatbuffers::VOffsetT = 6;
    pub const VT_I16_: flatbuffers::VOffsetT = 8;
    pub const VT_U16_: flatbuffers::VOffsetT = 10;
    pub const VT_I32_: flatbuffers::VOffsetT = 12;
    pub const VT_U32_: flatbuffers::VOffsetT = 14;
    pub const VT_I64_: flatbuffers::VOffsetT = 16;
    pub const VT_U64_: flatbuffers::VOffsetT = 18;
    pub const VT_F32_: flatbuffers::VOffsetT = 20;
    pub const VT_F64_: flatbuffers::VOffsetT = 22;
    pub const VT_V8: flatbuffers::VOffsetT = 24;
    pub const VT_VF64: flatbuffers::VOffsetT = 26;

  pub fn i8_(&'a self) -> i8  {
    self._tab.get_slot_scalar::<i8>(TypeAliases::VT_I8_, 0)
  }
  pub fn u8_(&'a self) -> u8  {
    self._tab.get_slot_scalar::<u8>(TypeAliases::VT_U8_, 0)
  }
  pub fn i16_(&'a self) -> i16  {
    self._tab.get_slot_scalar::<i16>(TypeAliases::VT_I16_, 0)
  }
  pub fn u16_(&'a self) -> u16  {
    self._tab.get_slot_scalar::<u16>(TypeAliases::VT_U16_, 0)
  }
  pub fn i32_(&'a self) -> i32  {
    self._tab.get_slot_scalar::<i32>(TypeAliases::VT_I32_, 0)
  }
  pub fn u32_(&'a self) -> u32  {
    self._tab.get_slot_scalar::<u32>(TypeAliases::VT_U32_, 0)
  }
  pub fn i64_(&'a self) -> i64  {
    self._tab.get_slot_scalar::<i64>(TypeAliases::VT_I64_, 0)
  }
  pub fn u64_(&'a self) -> u64  {
    self._tab.get_slot_scalar::<u64>(TypeAliases::VT_U64_, 0)
  }
  pub fn f32_(&'a self) -> f32  {
    self._tab.get_slot_scalar::<f32>(TypeAliases::VT_F32_, 0.0)
  }
  pub fn f64_(&'a self) -> f64  {
    self._tab.get_slot_scalar::<f64>(TypeAliases::VT_F64_, 0.0)
  }
  pub fn v8(&'a self) -> Option< &'a[i8] > {
    self._tab.get_slot_vector::<i8>(TypeAliases::VT_V8)
  }
  pub fn vf64(&'a self) -> Option< &'a[f64] > {
    self._tab.get_slot_vector::<f64>(TypeAliases::VT_VF64)
  }
}

pub struct TypeAliasesArgs<'a> {
    pub i8_: Option<i8>,
    pub u8_: Option<u8>,
    pub i16_: Option<i16>,
    pub u16_: Option<u16>,
    pub i32_: Option<i32>,
    pub u32_: Option<u32>,
    pub i64_: Option<i64>,
    pub u64_: Option<u64>,
    pub f32_: Option<f32>,
    pub f64_: Option<f64>,
    pub v8: Option<flatbuffers::VectorLabeledUOffsetT<VectorOffset>>,
    pub vf64: Option<flatbuffers::VectorLabeledUOffsetT<VectorOffset>>,
    pub _phantom: PhantomData<&'a ()>, // pub for default trait
}
impl<'a> Default for TypeAliasesArgs<'a> {
    fn default() -> Self {
        TypeAliasesArgs {
            i8_: None,
            u8_: None,
            i16_: None,
            u16_: None,
            i32_: None,
            u32_: None,
            i64_: None,
            u64_: None,
            f32_: None,
            f64_: None,
            v8: None,
            vf64: None,
            _phantom: PhantomData,
        }
    }
}
pub struct TypeAliasesBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::LabeledUOffsetT<flatbuffers::TableOffset>,
}
impl<'a: 'b, 'b> TypeAliasesBuilder<'a, 'b> {
  pub fn add_i8_(&mut self, i8_: i8 ) {
    self.fbb_.push_slot_scalar::<i8>(TypeAliases::VT_I8_, i8_, 0);
  }
  pub fn add_u8_(&mut self, u8_: u8 ) {
    self.fbb_.push_slot_scalar::<u8>(TypeAliases::VT_U8_, u8_, 0);
  }
  pub fn add_i16_(&mut self, i16_: i16 ) {
    self.fbb_.push_slot_scalar::<i16>(TypeAliases::VT_I16_, i16_, 0);
  }
  pub fn add_u16_(&mut self, u16_: u16 ) {
    self.fbb_.push_slot_scalar::<u16>(TypeAliases::VT_U16_, u16_, 0);
  }
  pub fn add_i32_(&mut self, i32_: i32 ) {
    self.fbb_.push_slot_scalar::<i32>(TypeAliases::VT_I32_, i32_, 0);
  }
  pub fn add_u32_(&mut self, u32_: u32 ) {
    self.fbb_.push_slot_scalar::<u32>(TypeAliases::VT_U32_, u32_, 0);
  }
  pub fn add_i64_(&mut self, i64_: i64 ) {
    self.fbb_.push_slot_scalar::<i64>(TypeAliases::VT_I64_, i64_, 0);
  }
  pub fn add_u64_(&mut self, u64_: u64 ) {
    self.fbb_.push_slot_scalar::<u64>(TypeAliases::VT_U64_, u64_, 0);
  }
  pub fn add_f32_(&mut self, f32_: f32 ) {
    self.fbb_.push_slot_scalar::<f32>(TypeAliases::VT_F32_, f32_, 0.0);
  }
  pub fn add_f64_(&mut self, f64_: f64 ) {
    self.fbb_.push_slot_scalar::<f64>(TypeAliases::VT_F64_, f64_, 0.0);
  }
  pub fn add_v8(&mut self, v8: flatbuffers::LabeledUOffsetT<&[i8]> ) {
    self.fbb_.push_slot_labeled_uoffset_relative(TypeAliases::VT_V8, v8);
  }
  pub fn add_vf64(&mut self, vf64: flatbuffers::LabeledUOffsetT<&[f64]> ) {
    self.fbb_.push_slot_labeled_uoffset_relative(TypeAliases::VT_VF64, vf64);
  }
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> TypeAliasesBuilder<'a, 'b> {
    let start = _fbb.start_table(12);
    TypeAliasesBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  // TypeAliasesBuilder &operator=(const TypeAliasesBuilder &);
  //pub fn finish<'c>(mut self) -> flatbuffers::LabeledUOffsetT<flatbuffers::TableOffset> {
  pub fn finish<'c>(mut self) -> flatbuffers::LabeledUOffsetT<TypeAliasesOffset> {
    let o = self.fbb_.end_table(self.start_);
    //let o = flatbuffers::LabeledUOffsetT::<TypeAliasesOffset>::new(end);
    flatbuffers::LabeledUOffsetT::new(o.value())
  }
}

#[inline]
pub fn CreateTypeAliases<'a: 'b, 'b>(
    _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    args: &TypeAliasesArgs) -> flatbuffers::LabeledUOffsetT<TypeAliasesOffset> {
  let mut builder = TypeAliasesBuilder::new(_fbb);
  if let Some(x) = args.f64_ { builder.add_f64_(x); }
  if let Some(x) = args.u64_ { builder.add_u64_(x); }
  if let Some(x) = args.i64_ { builder.add_i64_(x); }
  if let Some(x) = args.vf64 { builder.add_vf64(x); }
  if let Some(x) = args.v8 { builder.add_v8(x); }
  if let Some(x) = args.f32_ { builder.add_f32_(x); }
  if let Some(x) = args.u32_ { builder.add_u32_(x); }
  if let Some(x) = args.i32_ { builder.add_i32_(x); }
  if let Some(x) = args.u16_ { builder.add_u16_(x); }
  if let Some(x) = args.i16_ { builder.add_i16_(x); }
  if let Some(x) = args.u8_ { builder.add_u8_(x); }
  if let Some(x) = args.i8_ { builder.add_i8_(x); }
  builder.finish()
}

#[inline]
pub fn VerifyAny(verifier: &mut flatbuffers::Verifier, obj: &[u8], type_: Any) -> bool {
  match type_ {
    Any::NONE => {
      return true;
    }
    Any::Monster => {

      if obj.len() != mem::size_of::<Monster>() {
          return false;
      }
      let x: &Monster = unsafe {
        &*(obj.as_ptr() as *const Monster)
      };
      return verifier.verify_table::<&Monster>(x);
    }
    Any::TestSimpleTableWithEnum => {

      if obj.len() != mem::size_of::<TestSimpleTableWithEnum>() {
          return false;
      }
      let x: &TestSimpleTableWithEnum = unsafe {
        &*(obj.as_ptr() as *const TestSimpleTableWithEnum)
      };
      return verifier.verify_table::<&TestSimpleTableWithEnum>(x);
    }
    Any::MyGame_Example2_Monster => {

      if obj.len() != mem::size_of::<super::Example2::Monster>() {
          return false;
      }
      let x: &super::Example2::Monster = unsafe {
        &*(obj.as_ptr() as *const super::Example2::Monster)
      };
      return verifier.verify_table::<&super::Example2::Monster>(x);
    }
  }
}

#[inline]
pub fn VerifyAnyVector(_verifier: &mut flatbuffers::Verifier, values: &[flatbuffers::LabeledUOffsetT<flatbuffers::Void>], types: &[u8]) -> bool {
  //if values.len() == 0 || types.len() == 0 {
  //  return values.len() == types.len();
  //}
  if values.len() != types.len() { return false; }
  //for _i in (0 as flatbuffers::UOffsetT)..values.len() {
    //if !VerifyAny(
    //    verifier,  values.Get(i), types.GetEnum::<Any>(i)) {
    //  return false;
    //}
  //}
  return true;
}

#[inline]
pub fn GetRootAsMonster(buf: &[u8]) -> Monster  {
  //return flatbuffers::get_root::<&Monster>(buf);
  return flatbuffers::get_root::<Monster>(buf);
}

#[inline]
pub fn MonsterIdentifier() -> &'static str {
  return "MONS";
}

#[inline]
pub fn MonsterBufferHasIdentifier(buf: &[u8]) -> bool {
  return flatbuffers::buffer_has_identifier(
      buf, MonsterIdentifier());
}

#[inline]
pub fn VerifyMonsterBuffer(
    verifier: &mut flatbuffers::Verifier) -> bool {
  return verifier.verify_buffer::<Monster>(MonsterIdentifier());
}

#[inline]
pub fn MonsterExtension() -> &'static str {
  return "mon";
}

#[inline]
pub fn FinishMonsterBuffer<'a: 'b, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::LabeledUOffsetT<MonsterOffset>) {
  fbb.finish_with_identifier(root, MonsterIdentifier());
}

}  // pub mod Example
}  // pub mod MyGame

